### ISSUE TITLE
Error on testbench suite

### ISSUE THREAD

**Issue by BaseliyosJacob** [openETCS/modeling#192]
Dear all,

an error occurs on my notebook with the testbench suite after Start of Mission and start of running i get "stack overflow".

Are you aware of this issue?

**Comment by stefan-karg** [comment]
Dear Baseliyos,

we were also facing this problem today and we were trying to solve the problem together with Esterel. There is no final solution yet, since our data structures are too big to handle with SCADE (and too big for any embedded target...).

You can find a workaround for the in commit 5d5f4a9bc4d7d5d21041f011d4b5e263b788a0a7

To use the workaround select the SCADE code generation profile "CoSummit" instead of "Simulation". This newly created profile will compile a executable for the SCADE simulator without any debugging information (which means e.g. showing the current state in the state machine does not work any more).

This is just a workaround for the upcoming demos this week. We are still in contact with Esterel and trying to solve the problem together.

**Comment by BaseliyosJacob** [comment]
Dear Stefan, thank you very much for the answer. Will use this workaround for the Demos this week. Thanks

**Comment by BaseliyosJacob** [comment]
Dear Stefan, thank you very much for the answer. Will use this workaround for the Demos this week. Thanks

**Comment by BaseliyosJacob** [comment]
Dear Stefan, thank you very much for the answer. Will use this workaround for the Demos this week. Thanks

**Comment by BaseliyosJacob** [comment]
Dear Stefan, thank you very much for the answer. Will use this workaround for the Demos this week. Thanks

**Comment by BaseliyosJacob** [comment]
Dear Stefan, thank you very much for the answer. Will use this workaround for the Demos this week. Thanks

**Comment by BaseliyosJacob** [comment]
Dear Stefan, thank you very much for the answer. Will use this workaround for the Demos this week. Thanks

**Comment by BaseliyosJacob** [comment]
Dear Stefan, thank you very much for the answer. Will use this workaround for the Demos this week. Thanks

**Comment by BaseliyosJacob** [comment]
Dear Stefan, thank you very much for the answer. Will use this workaround for the Demos this week. Thanks

**Comment by BenjaminBeichler** [comment]
@stefan-karg 

I run again into stack overflows, so I propose beside the option of the global simulation context, also the option to mark local variables to static needs to be checked, or the debug information needs to be reduced.

**Comment by stefan-karg** [comment]
Dear Benjamin,

which profile did you choose to generate the application? 

For the next update (I'm currently improving the graphical panels), I will update the code generation profiles for more clear definition.
