### ISSUE TITLE
review cycle of ADD

### ISSUE THREAD

**Issue by faustco** [openETCS/modeling#234]
The ADD document is made out  of many separate "included" contributions.
A reasonable review cycle should act on the separate contributions.
Only contributes that have closed their review cycle should candidate to inclusion in ADD
The ADD document owner will manage a consistent inclusion / release policy.

**Comment by JakobGartner** [comment]
I have tried to consolidate this document during the last days.

I honestly believe that we should reconsider the way we do it, and also the scope of this document.
In the current form it tries to be too many different things at once.

We should split in two parts:

- A descriptive document of max. 40 pages that explains our main concepts and approach. 
This should be done by one person who digests the input instead of composing from diverse input.
I volunteer (on my own budget, as a direct LEA/Railergy project contribution)

- A more formal ADD document (which should be concise, structured like a requirements spec and linked to the model)

Here everybody can then write his contribution; as the text will be very technical, it will be easier to assure consistent quality 

- An auto generated document from the SCADE model. This will then also contain annotations pulled from the linked ADD.


Just my humble opinion…
And I know it comes very/ too late for the review.

Jakob
