### ISSUE TITLE
Test Model integration with CalculateTrainPosition

### ISSUE THREAD

**Issue by JakobGartner** [openETCS/modeling#255]
Logical issue:

- we have a balise channel
- we have a radio channel

at the moment, they are logically intertwined in the passedBG_T

in our example we may pass a BG -->  the valid flag in passedBG_T will be true
or we may receive a RBC message --> the valid flag in passedBG_T will also be true?

you have an additional level of valid flag in LinkedBG_T and also in BG_Header_T

as in the track model the channels are independent, I can produce the flags in LinkedBG_T and in BG_Header_T separately and I just OR them to produce the valid flag in passedBG_T

Is that ok for @UweSteinkeFromSiemens ?

I think @BerndHekele we should consider to build the Balise Channel and the Radio Channel as parallel constructs instead of creating one stream of data.
At least we may consider to merge the packets from the two channels at a later stage. 
We should follow the functional breakdown from Alstom here.

**Comment by JakobGartner** [comment]
@UweSteinkeFromSiemens : 
please check the operators SimulateOdometry and SimulateBaliseChannel.
Some open questions remain about the required data.

**Comment by JakobGartner** [comment]
@UweSteinkeFromSiemens:

the input of CalculateTrainPosition has a type LinkedBGsT.
This type is a mix of SRS 7.4.2.2. Packet Number 5  Linking and additional information (nid_LRBG)

To keep things consistent with the SRS we should separate the info about the LRBG here.

As a workaround, I provide an input to the read function where you can feed in the LRBG info.

**Comment by UweSteinkeFromSiemens** [comment]
Re. **passedBG_T** construct:
- passedBG_T comprises the header information (BG_Header_T) sent by a BG and an array of linking packets (packet 5). 
- Each of them - the header as well as each of the linking packets - is optional. The header and each of the linking packets are equipped with separate valid flags.
- A general valid flag (passedBG_T.valid ) designates that passedBG_T in general carries useful information. This valid flag in some way is redundant within the structure; it is true, if one of the underlying valid flags is true. 

This construction enables passedBG_T to inform calculateTrainPosition
- when a BG has been passed: the header only is valid.
- when a linked BG announcing more linked BGs ahead has been passed: the header and some linking packets are valid
- when linked BGs ahead are announced via radio: only some linking packets are valid. 

Announcing BGs via radio indispensably requires that the reference BG (= the current LRBG), the announced BGs are linked to, is known and therefore must have been overpassed by the train before. Since the LRBG is assigned by the OBU and reported to the RBC before it can be used by the RBC in an announcement, this precondition is met in realistic scenarios automatically and must be considered in simulated scenarios too. 

Re. **LinkedBG_T, LinkedBGs_T**:
- LinkedBG_T is a representation of a linked BG as announced by linking packet no. 5. 
- In order to ease the handling due to SCADE capabilties, the iteration within packet 5 has been unrolled into the array LinkedBGs_T. 
- The linking information from packet 5 is useless without the appropriate reference BG. The reference BG is the just overpassed BG (if packet 5 originates from a BG) or the current LRBG (if received via Radio) as reported by exactly the radio message that packet 5 belongs to. This is the reason why LinkedBG_T was enhanced with nid_LRBG. 
- Due to the asynchronism between train and track (OBU and RBC), the OBU LRBG and the RBC LRBG are not the same all the time, and the LRBG is changing during the trip anyway. This is, why the respective reference BG has to be preserved with the linking packet. 
- I don't mind if nid_LRBG would be removed from LinkedBG_T. But then, calculateTrainPosition needs the radio message header added to its inputs instead. 

For the **separation of balise and radio data paths** at its inputs, calculateTrainPosition would need
- BG header (equipped with pre-evaluated information comparable to BG_Header_T ) and linking packet 5 unrolled and stamped with odometry information from the balise data path
- radio message header and linking packet 5 unrolled from the radio data path

**Comment by UweSteinkeFromSiemens** [comment]
Re. **SimulateBaliseChannel*:
- BG_Header.bgPosition: odometry stamp: odometry values captured by the BTM subsystem when receiving the balise information. Within the OBU balise channel, the odometry stamp probably can be taken from balise 1 of the balise group.
- BG_Header.BG_centerDetectionInaccuracies: inaccuracy of the BG location as determined by the BTM subsystem
- q_nvlocacc: default national value for the balise mounting inaccuracy Should be constant for Utrecht-Amsterdam. q_nvlocac in general originates from the NV packet, is a location based datum and may change with every BG. 
- BG_Header.noCoordinateSystemHasBeenAssigned: marks a BG without a direction (BG consisting of 1 balise). Should be set to false for Utrecht-Amsterdam.
- BG_Header.trainOrientationToBG: characterizes the train orientation (which cab is activated) with reference to the BG orientation. Has to be set appropriately to the train and BG orientation during the trip.
- BG_Header.trainRunningDirectionToBG: characterizes the train movement direction with reference to the BG orientation. Has to be set appropriately to the train movement direction (determined from train orientation and odometry) and BG orientation during the trip.

**Comment by UweSteinkeFromSiemens** [comment]
Re. **SimulateOdometry**:
- calculateTrainPosition needs from odometry_T 
  - odometry_T.odo: odometry location values with inaccuracies. The nominals values have to be increasing when the train moves into its regular direction: if cab A is active, the values increase with moving into cab A direction. 
  - odometry_T.motionState: 
  - odometry_T.motionDirection: currently speed is used by calculateTrainPosition, but make use of motionState and motionDirection instead very soon.

- The simulation should be based upon "true" locations (exact locations without any inaccuracies) and time. Inaccuracies should be then added by modelling the inaccuracy behavior explicitly for location and speed. 
- The absolute location inaccuracies must be monotonically increasing. 

- For calculateTrainPosition it is sufficient to derive odo, motionState and motionDirection from a true location and activeCab input. 
- For a more general approach it might be more practically appropriate deriving all odometry information from time, "true" acceleration and activeCab inputs.

**Comment by BerndHekele** [comment]
@JakobGartner : Regarding your question on speeration of the channels:

The separation of the channels yould be an option.In this scenario we need the merge function straight before the  validate data direct block. We considered this as a design choice.

Our chosen solution was based on the argument you needa message buffer in at least one place to avoide collisins of incomming messages . And we think the API handling the messages is the best place for this buffer since messages have to be stored in this place anyway.

The design allows easy separation of the channels now - but I still see the argument of the message buffer in the merge function.
