### ISSUE TITLE
Modeling Guidlines SCADE for Requirements

### ISSUE THREAD

**Issue by BenjaminBeichler** [openETCS/modeling#275]
the modelling guideline should be updated, so that also *.trace, *.rqtf and *.rqtfimage files should be included in git.

**Comment by janWelte** [comment]
I've to agree. This files are need to provide traceability.

**Comment by T12z** [comment]
I am not sure about the _*.rqtfimage_ files as they seem to be kind of cache. If they are missing, they are recreated (which takes a few seconds). It is quite a bit of a binary blob and it seems they change even though no content was changed. I vote for **ignoring** them unless someone can state that they contain unique, unrecreatable data.
cheers T.

**Comment by janWelte** [comment]
The *.rqtfimage files are a little in bitween. 
The do not present unique data, as they are the snap shot of all requirements tags of related documents. Therefore, they are always recreated if the documents are scanned again, which can be triggered by changes and manually.
With respect to this, we usually should not include these files. But for projects covering many requirement tags it can take quite some time to recreate the file, which makes it extremely tedious to work without the file. That's why I would include the file.

**Comment by BenjaminBeichler** [comment]
I agree with thorsten, **not to include** this thing to git, since it changes much every time a project is opened. Since also the untracked file stays in a directory it would take only long time, when the project is freshly cloned, or the file was deleted, which has the intent to create the file new.

**Comment by janWelte** [comment]
This is a correct point. As most people should be set up after one run we should leave them out.

**Comment by BenjaminBeichler** [comment]
I propose to use the .gitignore file, as we use in speed supervision to not accidentally add this files

**Comment by janWelte** [comment]
Marc already proposed to use *.gitignore for all not wanted SCADE files. From a process stand view this would be the best solution

**Comment by UweSteinkeFromSiemens** [comment]
I added the requirements gateway files needed for version control to https://github.com/openETCS/modeling/blob/master/ModelingRules/SCADE_Modelling_Guide.pdf.
