### ISSUE TITLE
Limit file length of github reporitory to a total of 100 character to avoid checkout errors within window systems

### ISSUE THREAD

**Issue by MarcBehrens** [openETCS/modeling#303]
After several checkout errors within a windows document structure, this is a reaquest to reorganize the folder structure to reduce the total file and folder charaters to not more than 100.

Found within: modeling/model/Scade/System/TracksideDynamicModel/TestTracks/UtrechtAmsterdam_oETCS/UtrechtAmsterdam_oETCS_newmapping.h

**Comment by BerndHekele** [comment]
Hi Marc,
what is the background of this request?

Bernd

**Comment by MarcBehrens** [comment]
The background are the checkout errors I have seen at several windows systems when the pathname gets too long. This way parts of the files resiging inside a folder which accumulates to about 120 characters (full local directory name + filename) is not checked out at all.

**Comment by MarcBehrens** [comment]
![150512_windowserror_filenametoolong](https://cloud.githubusercontent.com/assets/2271821/7588155/86412064-f8bb-11e4-8596-a439d1057f10.jpg)

error found during copying the repository.
The same error is reproduced while checking out files inside the repository.

Reproducibility: 100%

Tested on System: Windows 7 Enterprise, Service Pack 1 on a NTFS formatted file system copying with the Windows-Explorer version 6.1.7601.17567

Numbers of characters in path, excluding the filename when the model stopped compying including '\': 154

**Comment by BenjaminBeichler** [comment]
This is a problem of the WindowsAPI and of course depends on the path you put the this subfolder.

This is no restriction of NTFS itself, but the program to copy files. So as a workaround you could use a folder to drive-letter mapping (http://superuser.com/questions/644684/mapping-drive-letters-to-local-folders) 

But its a bit confusing that it already breaks at 154 Characters, since WindowsAPI seems to allow 260 characters (https://msdn.microsoft.com/en-us/library/aa365247.aspx).

However more concrete naming conventions and maybe a more flat hierarchy (especially for the SCADE Model) would be nice to avoid such problems and make the model a bit easier to understand.

**Comment by MarcBehrens** [comment]
Recommendation to the use of github:

- Use meaningful abbreviations for directories
- Avoid redundancies in the names of directories
- Use meaningful names for filenames
- Limit the maximum component length [1] counting tha characters starting from the modeling repository and ending with the file extension to 200 characters.
- Using Windows: Limit the relative pathlength where you check out the repository to 50 characters [1] [2] 

This is done to ensure that the maximum component length on a windows system does not exceed 255 characters.

[1] https://msdn.microsoft.com/en-us/library/aa365247%28VS.85%29.aspx
[2] https://en.wikipedia.org/wiki/Comparison_of_file_systems#Limits

**Comment by BerndHekele** [comment]
Related to old release
