### ISSUE TITLE
US-SpeedMonitoring: Dynamic ASave Calculation

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#312]
Called in the SRS calculation of decelaration.

With the model different gradients and track conditions can be calculated.
Track dependent decceleration of the train.

First Step Low adhesision parameter and gradient profile.
Impact on train model also necessary.

Lambda Train Parameters are not considered in the next iteration.

DMI impact (planning area) needs analysis of requirements. Driver is the DMI.

**Comment by BenjaminBeichler** [comment]
@JakobGartner 

is there an stable definition of A_Gradient in the modelling repository ?

**Comment by JakobGartner** [comment]
there is no calculation of A_gradient yet.

The type for the gradient profile is however stable, unless you need a change.


We had concentrated on the data transport after finishing the MRSP calculation… 
We should discuss priorities…

What are you exact needs?

**Comment by BenjaminBeichler** [comment]
@JakobGartner 
OK then I would implement the A_Gradient Calculation in the Speed Supervision Operator. Therefore only the gradient profile is needed.

In the TrackAtlasTypes.etp is a GradientProfile_t, but the comment says, it is train length and rotating mass compensated. If the calculation of §3.13.4.3.2 is already done (which implies that comment), we have A_gradient. Otherwise could you change your comment and I will use that type. 

I think to be conform to other projects, the types of TrackAtlas should be in a Package to have a separate namespace. Since MA and MRSP is already used, this change needs to be coordinated ...

I don't know the usage of that types yet, but I think @stefan-karg @BerndHekele also use this types as well as the balise processing group (I dont know the persons ...)

**Comment by BenjaminBeichler** [comment]
As decided at the Stuttgart-Group-1 Meeting, the effort to calculate A_Gradient is switched from @JakobGartner  to Group one or more specifically myself.

Therefore the current tasks are the A_gradient_calculation:
- [ ] Train Length compensation
- [ ] Calculation of Influence of Gradient caused by non rotating mass

**Comment by BenjaminBeichler** [comment]
@JakobGartner 

As I try to complete my work on A_Gradient, I need to rework my Datatype imports and I was wondering about the description of "GradientProfile_t". There is still the desciption this data is train length compensated. Could you correct this ?

**Comment by T12z** [comment]
implemented at least since September
