### ISSUE TITLE
CalculateTrainPosition: Test Environment + Balise Channel + Radio Reception ready to go ?

### ISSUE THREAD

**Issue by UweSteinkeFromSiemens** [openETCS/modeling#319]
CalculateTrainPosition requires the following prerequisites for starting with tests: 

- a test track equipped with linked balises and linking packets sent by balises or via radio
- the OBU balise input channel receiving balise information and forming balise group datagrams with BG header and linking packets
- generation of radio header and linking packets adjusted to the current LRBG and sent to the OBU
- odometry simulation providing the odometry locations consistent with the generated test track and radio transmission
- current system time consistent with the test tracks balise balise and radio transmission
- the ability to drive the train along the track. 
- the referred components integrated to a test bench

@JakobGartner, @BerndHekele , @stefan-karg: Please awake me as soon as the environment has been prepared so far.

**Comment by JakobGartner** [comment]
Point 1 is there

Story00A



On 27.04.2015, at 12:01, Uwe Steinke <notifications@github.com> wrote:

CalculateTrainPosition requires the following prerequisites for starting
with tests:

   - a test track equipped with linked balises and linking packets sent by
   balises or via radio
   - the OBU balise input channel receiving the balise information and
   forming balise group
   - the odometry

—
Reply to this email directly or view it on GitHub
<https://github.com/openETCS/modeling/issues/319>.

**Comment by BerndHekele** [comment]
Status-Update:
 - we now have a working model for passing level 1 linking information and bg-messages  to calculate train postion.
 - you could start testing now in the Balise group test model. But I would recommend to wait until we have the proper environment model. This activity is still ongoing.

**Comment by UweSteinkeFromSiemens** [comment]
I will then wait for the environment model.

**Comment by janWelte** [comment]
Same for me, as I need the odometry. Do you have a time plan, as I would love to undestand how I can best run systematic verificcation tests using the environment.

**Comment by BerndHekele** [comment]
Dear Jan,
I believe the small test model should be fine for your testing. The odometry is sufficentlyx supported to proceed on the track in time and distance.
The model is actually implemented for test you plan to run.
I can give you an introduction to it.

**Comment by UweSteinkeFromSiemens** [comment]
I'm going to wait what I get (and be surprised). 
@janWelte: Probably you should control the genesis and fit it to your needs ...

**Comment by janWelte** [comment]
I cannot run the simulation oder normal Simulation configuration (only under open Simu profil). 

It seam to me that the reasons are some inapt declarations of operators (probably in BGConsistency) as notes or functions, which result in not iso conform code. 
If with is not only happening at my machine, we should maybe fix this points to improve performance.

**Comment by JakobGartner** [comment]
What do you mean “I cannot run the simulation?”

SCADE uses a specific environment to build simulator executables. This code does never run standalone, only within the simulation wrapper (be it graphical or batch mode)
For generating code that runs standalone (which is then also much more compact because it’s without all the instrumentation required for the simulator, you need to generate the code with KCG,

However, you can increase the efficiency of the simulation (by reducing visibility) through changing code generation options.
If needed, I can guide you there.

**Comment by janWelte** [comment]
Thank you Jakob,

Bernd already helped me and it seems to be a small problem on my machine. 
As I finally got the access for my SCADE support Account I should be able to fix it in no time. 

But good to know that everyone is up to grasp this fast. Thanks.

Best regards

Jan

-----Ursprüngliche Nachricht-----
Von: Jakob Gärtner [mailto:notifications@github.com] 
Gesendet: Donnerstag, 30. April 2015 09:24
An: openETCS/modeling
Cc: Jan Welte
Betreff: Re: [modeling] CalculateTrainPosition: Test Environment + Balise Channel + Radio Reception ready to go ? (#319)

What do you mean “I cannot run the simulation?”

SCADE uses a specific environment to build simulator executables. This code does never run standalone, only within the simulation wrapper (be it graphical or batch mode)
For generating code that runs standalone (which is then also much more compact because it’s without all the instrumentation required for the simulator, you need to generate the code with KCG,

However, you can increase the efficiency of the simulation (by reducing visibility) through changing code generation options.
If needed, I can guide you there.

**Comment by BerndHekele** [comment]
Hi Uwe,
can we close the issue now?

cu
Bernd

**Comment by UweSteinkeFromSiemens** [comment]
We should not close it as long as the TestBenchExample has not been passed without inconsistencies.

**Comment by UweSteinkeFromSiemens** [comment]
Out-dated.
