### ISSUE TITLE
Agenda Working Group1 Meeting in Stuttgart 

### ISSUE THREAD

**Issue by christianstahl** [openETCS/modeling#320]
Dear All,

the information for the Stuttgart workshop can now also be found in the wiki: https://github.com/openETCS/modeling/wiki/Workshop-Working-Group1-in-Stuttgart-%28May-6th----May-7th-2015%29

If there is any other topic you would like to put on the agenda, please add it.
Christian

@vgontier @BenjaminBeichler @T12z @faustco @BerndHekele @BaseliyosJacob @JakobGartner @srieger

**Comment by T12z** [comment]
Dear all (@vgontier @faustco @BerndHekele ),

due to the current notification of a strike of the German train drivers :station: for the next few days I see myself unable to get to the meeting in Stuttgart. I am really sorry - I have already checked a few alternatives, but so far they are just not reliable or on a reasonable scale.
If I happen to find something, I will keep you updated.

**Comment by vgontier** [comment]
DB strikes are especially planned during Open ETCS meetings.
I hope I will arrive...

**Comment by mahlmann** [comment]
Issue will be closed since the meeting has been held already.
