### ISSUE TITLE
Speed and Distance Monitorin: Compile Errors in Model

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#344]
@BenjaminBeichler , @christianstahl  @T12z 

I get an Err_8 out of the folliwing models:

SpeedSupervision_Integration_Pkg::SpeedSupervision_Integration/MRSP/
SDM_Types_Pkg::getMRSFromMRSP
TargetManagement_types::Target_list_LOA_real_T
SDM_Input_Wrappers::SDM_InputWrapper/MRSP/
CalcBrakingCurves_Pkg::CalcBrakingCurves_integration/MRSPCurves/

and some others.
Can you please correct the models.

kr
Bernd

**Comment by BenjaminBeichler** [comment]
fixed by add0c51d0da75bdbf609f1a66a9e3ce118a73874

@JakobGartner @BerndHekele 

Please create temporary branches, when changing things which affect other operators ... We are not able to always adjust things with light speed and I think we agreed on a working master branch. Same is valid for pull-request... when they are untested the master branch fastly becomes bad.

**Comment by BerndHekele** [comment]
Thanks
