### ISSUE TITLE
doTestTrackSideIntegration can lose balises due to different timing and missing stacks

### ISSUE THREAD

**Issue by janWelte** [openETCS/modeling#353]
If a BG with numerous telegrams is send (more than 2) with the current configuration only some of them are transmitted via BTM to the OBU.

The logic of Story00A_BTM to release telegrams based on the odometry input jumps telegrams if the distance covered in one cycle is to big.

**Comment by JakobGartner** [comment]
The Balise Group simulation operator is currently designed to handle one balise per model cycle. 
If the distance covered by the train within one cycle is larger or equal than the distance between the balises in a BG, Telegrams will not correctly be fired.

In order to enhance this, the logic to send the Telegram Headers would have to be changed.
This would also mean that the balise/radio input channels would have to be enabled to handle more than one telegram header per cycle.

---> It is better to adapt the ratio between inter-balise distance and the distance covered by the train within one simulation cycle for now.

In contrary to that, the number of packets that can be sent during one cycle is only limited by the data elements and the max number of metadata elements defined in the corresponding data type.

**Comment by JakobGartner** [comment]
@BerndHekele @mairamou 
you should find the right size for the corresponding dimensioning constants.

**Comment by UweSteinkeFromSiemens** [comment]
Please adhere to the rules in https://github.com/openETCS/modeling/blob/master/ModelingRules/SCADE_Modelling_Guide.pdf, chapt.3.6. Then, you will never run into such kind of problems.

**Comment by janWelte** [comment]
Jakob, thanks for your clarification. This is exactly why I assigned this issue to Bernd, as this question, IMHO, is only related to the testgenerator and which parameter determines the cycle. 

At the moment the cycle is linked to the speed, which results in long cycle times. Maybe the model should be adopted to set a smaller cycle time to transmit all telegrams at any reasonable speed. (Transmission errors should be specified in tests and not created by model limitations.)

I just wanted to discuss this to create progress.
Jakob, thanks for your clearification. This is exactly why I wanted to added this, as

**Comment by JakobGartner** [comment]
This issue is purely on specification level (in the simulation domain) and applies only if the distance travelled by the train within one cycle is larger than the distance between 2 balises.

**Comment by janWelte** [comment]
As this issue has been fixed I can close the issue
