### ISSUE TITLE
CheckEuroRadioMessage: is to determine the last relevant event time stamp part of this function?

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#363]
The variable is used only in this check and all messages are passed.
Do we need more information?

**Comment by stefan-karg** [comment]
The input "lastRelevantTimestamp" is needed in order to check timeouts.

In most of the cases, the timestamp of theh last relevant event is the timestamp of the last message received. But the SRS defines special cases like driving through a defined radio hole. In this case, the timestamp of the last relevant event is the point of time, when the EVC has a radio connection again.

My assumption was that the timestamp of the last relevant event will be in future stored in the database, since data from multiple sources has to be collected and combined (e.g. from the reception module, from the radio management module, etc.)

How should we proceed with this variable?

**Comment by BerndHekele** [comment]
Thanks for the response.
Does the SRS request to calculate the estimated time based on infomration available (e.g., some packet)?

**Comment by stefan-karg** [comment]
Three conditions are defined by the SRS (paragraphs: 3.16.3.4.1.1 - 3.16.3.4.1.3):

* Level transition to L2 or L3 without established radio communication: use timestamp of level transition
* Announcement of RBC-handover: Until the accepting RBC is not the supervising RBC, the timestamp of the last message received from the handing over RBC shall be used.
* Announced radio hole: timestamp of passing the end of the radio hole with the front end of the train

The calculation is a more complex operation which needs data from several sources. According to the description I can identify the following modules involved:

* Mode/Level-management
* Radio management module
* Database in case information about announced radio holes is stored there (?)

**Comment by BerndHekele** [comment]
Done.
Might be revisited when discussing a new design.
