### ISSUE TITLE
Testtrack Utrech-Amsterdam does not throw balise telegrams when the train is driving to fast.

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#379]
When the position is incremented in too big steps (like running a fast train) some balises are not generated.

Can be reproduced using the test-example.

https://github.com/openETCS/modeling/tree/master/model/Scade/System/OBU_PreIntegrations/TestBenchExample

**Comment by janWelte** [comment]
This is probably the same cause as in #353.
This problem is based on the fact, that the track description triggers balises only is they are just past and at maximum one per cycle. If the train covers more than one balise per cycle some are lost. 
As I've discussed with Jakob this should be handled by setting separating cycle time and to reach reasonable cycle times for the BTM input. It is a reasonable assumption that only one balise per cycle is passed (140 Hz are need to to lose a balise with 1 m distance and max. 500 km/h).
We should discuss if we want to change the testgenerator this way 
This is probably the same cause as in #353.
This problem is based on the fact, that the track discription triggers balises only is they are just past and at maximum one per cycle. If the train covers more than one balise per cycle some are lost.

**Comment by UweSteinkeFromSiemens** [comment]
This is one of several reasons why constant period clocking is not appropriate in most cases.

**Comment by JakobGartner** [comment]
this should be fixed through the actions by @stefan-karg
