### ISSUE TITLE
RBC requirements regarding ETCS Baseline

### ISSUE THREAD

**Issue by aprobst** [openETCS/modeling#471]
Today I had a discussion with Bernd about the requirements of the RBC regarding the ETCS Baseline. From a personal point of view, I think that the RBC should operate with Baseline 3 for beeing in accordance with the requirements of the openETCS project. Looking at the current version of TrackMessages.etp, I recognized that also functionalities of Baseline 2 are available. Also, I recognized that the provided operator TM_old_versions::SEND_MergeRadioPackets by @mairamou accepts now for the packets 3 and 27 only a Baseline 2 compatible format. Knowing that the RBC on the line Utrecht-Amsterdam operates in real life with Baseline 2, I am still confused.

I think this is an important issue and it should be clarified which Baseline should be used for the RBC model and the current user stories 7 - 12. I think that this problem also affects the EVC model.

@BaseliyosJacob 
@BerndHekele 
@Farhangi 
@JakobGartner 
@MarcBehrens 
@mairamou

**Comment by MarcBehrens** [comment]
Since the track Amsterdam-Utrecht is a baseline 2 track and the openETCS OBU is a baseline 3 OBU there should be no compatibility issues.

Concerning the test specification of the user stories 7 to 12 there will be also baseline 3 packets available.

Bottom line is that the openETCS OBU has to be able to read both, the basleine 2 and baseline 3 track messages.
