### ISSUE TITLE
BCD numbers should be stored as numerical string not as integer

### ISSUE THREAD

**Issue by didierersa** [openETCS/modeling#490]
Currently, BCD variable like Driver ID are stored as an integer. Entering value like '0000' would be converted as '0' integer which is wrong. All BCD variable must be kept as numerical string.

**Comment by stefan-karg** [comment]
This applies to:
- NID_MN
- NID_DRIVER
- ...

**Comment by BerndHekele** [comment]
Can you please be more precise on the expected format?
Can you give an example?

Thanks
Bernd

**Comment by BaseliyosJacob** [comment]
Dear Didier,

what is meant by BCD and do you have a reference in the specification requirements to this issue?

Thank you

Baseliyos Jacob

**Comment by stanpinte** [comment]
@BaseliyosJacob Dear bas, BCD = https://en.wikipedia.org/wiki/Binary-coded_decimal

Very kind regards

Stan

**Comment by didierersa** [comment]
To be more precise, every SRS variable coded in BCD format (thanks Stan for the wikipedia link), for example driver id, phone number, etc.. (the complete list is well documented in the subset 26),  should be kept as a "string" or numerical character array. For example, a driver can have an id defined as (hexadecimal binary data) 0x00000..01 which should not be converted in the integer value "1", but the string "0000..01". After looking a bit around some of the type definitions, we saw that some "BCD" variables are defined as "int" in the scade models, that's why we open an issue about it.

I hope it is clearer, if not, feel free to ask more details.

**Comment by BaseliyosJacob** [comment]
Hello Didier,

thanky you very much for your clarification. I am wondering if you can provide me the § in the subset 26. This helps me to be sure that i am analyzing the right scope.

Thank you very much

**Comment by BaseliyosJacob** [comment]
Dear Didier,

can you furthermore please assign this issue to somebody. If you dont know who is in charge of this issue, you can assign it to me and i will find the right person. But it is very important to assign issues to somebody.



Thank you very much

**Comment by stefan-karg** [comment]
Dear Baseliyos,

an example for such a BCD value is the variable NID_MN (7.5.1.91.1). 

The definitions are defined in chapter 7, you can find them there by searching for the term "Binary Coded Decimal".

**Comment by JakobGartner** [comment]
I think it should be assigned to me unfortunately



On 25 juin 2015, at 09:09, Baseliyos Jacob <notifications@github.com> wrote:

Dear Didier,

can you furthermore please assign this issue to somebody. If you dont know
who is in charge of this issue, you can assign it to me and i will find the
right person. But it is very important to assign issues to somebody.

Thank you very much

—
Reply to this email directly or view it on GitHub
<https://github.com/openETCS/modeling/issues/490#issuecomment-115157319>.

**Comment by BerndHekele** [comment]
Maybe you have a look at the assignement before making such an issue out of it.
I picked the issue from the start.
I'm aware the items are not well defined in some of the interfaces.

I just neeeded a clarification which of the definitions in the system have been dicovered.

cu
Bernd

P.S.: I will make the correction in the section 7 model.

**Comment by BerndHekele** [comment]
One remark to the definition:
actually - from telecommunication - the type is a binary coded digit rather than decimal  Some of the values between 10 and 15 are used for signalling information in the old fashioned analog telephone systems.

**Comment by BerndHekele** [comment]
Also relevant for NID_OPERATIONAL, NID_RADIO,

**Comment by BerndHekele** [comment]
I checked the consequences for our model.
Severl models need to be changed to work with the corrected interfaces.

I propose to defer this change to be nicely sorted out in the next iteration.
Please, reply to this proposal.

**Comment by christianstahl** [comment]
I agree. We should fix this during a model freeze.

**Comment by JakobGartner** [comment]
I agree




On 26 juin 2015, at 12:07, Bernd Hekele <notifications@github.com> wrote:

I checked the consequences for our model.
Severl models need to be changed to work with the corrected interfaces.

I propose to defer this change to be nicely sorted out in the next
iteration.
Please, reply to this proposal.

—
Reply to this email directly or view it on GitHub
<https://github.com/openETCS/modeling/issues/490#issuecomment-115648671>.

**Comment by didierersa** [comment]
I agree, I guess this should be done in a "one" pass when the model is somewhat frozen, not when everything change. It could be a good idea to define a "global" type for this.

**Comment by BerndHekele** [comment]
Many Thanks.
One last statement: we have the concept of global types. we can add this BCD immediately.
But since the NID_... alre also defined as global types changin them is a bit of destabilizing.

cu
Bernd

**Comment by didierersa** [comment]
Since all variables (NID...) that are BCD coded can have different size, I guess they should be defined as an array of a "BCD" char type which can have a value from char '0' to '9' plus 'a' to 'f' with the range 'a' to 'e' as reserved values and 'f' as padding. I don't know if you can be so precise in Scade type definition, but it should be correct. Anyway, a simple char array, without checks will be enough I guess.

**Comment by JakobGartner** [comment]
As we all agreed to defer this question to *after* the milestone concerning
the current set of user stories (we are late anyway) we should also defer
this thread.

A short general remark.
- such low - level type definitions are available from KCG R16 and the
corresponding new SCADE language.
We are working using the prior SCADE language set.

As this is a relatively isolated issue I propose to NOT migrate to the the
new language.

A mores abstract mechanism will be provided in the TrackMessages library
after we have passed the pending milestone. This will also cover issues
such as Q_MARQSTREASON where the current ENUM - based types are not really
the answer.

For the current user stories the current integer based implementation is
sufficient as the available JRU dataset also provides simplified integer -
based information only.


On 29.06.2015, at 08:40, didierersa <notifications@github.com> wrote:

Since all variables (NID...) that are BCD coded can have different size, I
guess they should be defined as an array of a "BCD" char type which can
have a value from char '0' to '9' plus 'a' to 'f' with the range 'a' to 'e'
as reserved values and 'f' as padding. I don't know if you can be so
precise in Scade type definition, but it should be correct. Anyway, a
simple char array, without checks will be enough I guess.

—
Reply to this email directly or view it on GitHub
<https://github.com/openETCS/modeling/issues/490#issuecomment-116479329>.

**Comment by BerndHekele** [comment]
Will be deferred to the next project.

**Comment by BerndHekele** [comment]
Interfaces are frozen.
