### ISSUE TITLE
US-interface of DMI Planning Area function with Track Atlas

### ISSUE THREAD

**Issue by BaseliyosJacob** [openETCS/modeling#496]
@JakobGartner @BerndHekele To test the DMI Planning Area i need the interface to the Track Atlas (Gradient End, Gradien Begin, Gradient Value, MRSP, ..)

**Comment by JakobGartner** [comment]
The values are are available via a direct interface.
The bus interface will be integrated later. (Not essential for this
milestone )

Jakob



On 27.06.2015, at 08:53, Baseliyos Jacob <notifications@github.com> wrote:

@JakobGartner <https://github.com/JakobGartner> @BerndHekele
<https://github.com/BerndHekele> To test the DMI Planning Area i need the
interface to the Track Atlas (Gradient End, Gradien Begin, Gradient Value,
MRSP, ..)

—
Reply to this email directly or view it on GitHub
<https://github.com/openETCS/modeling/issues/496>.

**Comment by BaseliyosJacob** [comment]
Dear Jakob,

thank you very much for the information.

@BerndHekele do you have sufficient information from Jakob to connect it with the DMI Manager to the DMI Controller??

**Comment by BaseliyosJacob** [comment]
- [ ] Analysis
- [ ] Modelling
- [ ] Documentation
- [ ] Handover to V&V
- [ ] Approval from V&V

**Comment by BerndHekele** [comment]
Since the interface is now available in the track-atlas we can start working on this isssue.
@BaseliyosJacob : I could not find the types you are using in your function on the DMI-Controller.
Can me tell me where this function is implemented and which types are used on your implementation.

I have seen the DMI-Types Types - but I'M not sure you are using them directly.

kr
Bernd

**Comment by BerndHekele** [comment]
@BaseliyosJacob 

I had a closer look at the actual interface.
The gradient profile in the DMI definition is buggy and needs correction.
I propose to  take the trackAtlas definition since we dicussed this before but I could also change to the original ERSA definition.

The speed profile needs some adjustment. Lets have a short discussion on Monday to define the best fitting interfaces in a small table session..

kr
Bernd

**Comment by BerndHekele** [comment]
The interface in the DMI_Types is corrected now.
@JakobGartner : I had to redefine the types due to model dependencies.
If we transfer the types we can transport them directly (proposal for next Iteration).
For now I will make some copy operator..

**Comment by BerndHekele** [comment]
Done.
