### ISSUE TITLE
MA_Request: Interface to DMI

### ISSUE THREAD

**Issue by christianstahl** [openETCS/modeling#498]
Dear Bernd @BerndHekele ,

according to 3.8.2.7 "an MA request shall be to the RBC when the driver selects start." How does selecting start is reflected by the DMI interface?
Thanks,
Christian

**Comment by BaseliyosJacob** [comment]
Dear Christian @christianstahl, 

selection of the start will be triggered by the DMI, but the trigger for the MA request will come from the Procedure. In the case the driver selects start a bool trigger as signal will be send from the Procedure to the MA Management (Request). The interface is not defined yet, since there was no function to interface and therefore it is just a boolean trigger. 

But you can define a interface in your MA Management and i will send you the trigger signal from the procedure. 

Does this help you?

**Comment by christianstahl** [comment]
Yes, it does! Thank you @BaseliyosJacob !

**Comment by BerndHekele** [comment]
@Christian: just define an appropriate input for the trigger (bool).
@BaseliyosJacob : we already use the start received information in the model (this is part of the dmi-status). I'm not convined we need an extra imput.

**Comment by BerndHekele** [comment]
Hi Christian,
I just integrated your model to the EVC.
When looking into your interface to the DMI a question for clarification:
Do you need a status for the two events or do you need a trigger?
I assume you really need a trigger. (indicated once when the change happens)

**Comment by christianstahl** [comment]
Hi Bernd,
I actually need a trigger.
Cheers,
Christian

**Comment by BerndHekele** [comment]
Done.
