### ISSUE TITLE
Definition of T_TRAIN

### ISSUE THREAD

**Issue by stefan-karg** [openETCS/modeling#519]
Currently, the RBC implementation uses an integer value for representing the T_TRAIN value with a resulution of 10 ms (T_TRAIN = 135 --> 1350 ms) while the EVC uses a real value (e.g. 1.35 s).

We should align the definition in the EVC to the definition used in the RBC.

**Comment by aprobst** [comment]
Hello Stefan. I think you mean that you receive a CompressedRadioMessage with an integer representation of T_TRAIN. According to the SRS, this is a correct approach. However, making calculations with an integer representation and thinking always about the 10ms resolution in every situation can cause headaches. I think the representation of T_TRAIN as a real is a good approach because it is easier to think in seconds. I use always T_TRAIN for internal purposes and calculate in seconds.

I recommend you to use the converter in Jakob's TM library, which converts the integer representation to T_TRAIN. I think changing everything in the EVC does not give any added value. It makes everything much more complicated.

**Comment by JakobGartner** [comment]
There are always two views:

Trackside
Trainside

While the values are ALL integers, BCD or bits on trackside, the SRS provides clear indications how this things are to be converted.
The TrackMessages library correctly converts all theses things. (I hope)
Most of the variables stay integers after conversion (with the main exception of the D_ and L_ variables) but they already have the correct scaling factor,

There should be no need to use any of the conversion operators on variable level. 
If you want to read a packet from the message stream, use the operators from TM (or from TM_baseline_2 where applicable)
If you want to read a message, use the operators from TM_radio_messages for conversion (high-level extraction operators are still in work)

Remark.

TrackMessages still has some limitations, but interfaces should be quite stable now and packet and message coverage is complete as far as Amsterdam- Utrecht is concerned.

**Comment by MarcBehrens** [comment]
Please use the 32 bit integer representation  with a resolution of 10 ms each integer increment within the package transferred to trackside via T_TRAIN. 
Is there already a timing concept for the EVC software concerning:
 - how fast the EVC cycle schould be triggered?
 - which resolution the EVC internal clock has?
Basically T_TRAIN should be derived directly from the internal EVC clock.

**Comment by stefan-karg** [comment]
After discussing the issue again with Bernd, we decided to stay with real in order to minimize the effort which would be needed to adjust the models. Since we are not developing a SIL 4 model in the current iteration, the use of real is not an issue.

@MarcBehrens : The concrete timing concept was not yet decided, but we are aware of that issue. 

Currently we have a 10ms constant cycle applied by the SCADE simulator to the whole integration model (including the environment simulation and track description).

This concept has to be changed for two reasons:
1. 10 ms cycle time are not enough to finish all necessary calculations within the EVC (e.g. the braking curve calculation will take more time).
2. Some modules (e.g. the MoRC module) need more than one cycle to calculate valid results. These multiple cycles needed for the EVC internal calculations might be - depending on the requirements of the module - executed within one EVC cycle period ( = the timestamp is not incremented but the model is cycled multiple times).

**Comment by JakobGartner** [comment]
This is compatible with the TrackMessages conversion function, however according to SRS, the resolution is 10ms:

**Comment by JakobGartner** [comment]
<img width="607" alt="screen shot 2015-07-03 at 11 04 13" src="https://cloud.githubusercontent.com/assets/8400941/8501254/2947558a-217a-11e5-83a1-6b4912d95c4c.png">

**Comment by JakobGartner** [comment]
remark:

the simulator cycle has nothing at all to do with a eventually to-be-chosen system cycle.

**Comment by MarcBehrens** [comment]
According to CENELEC EN50128 The "Strongly Typed Programming Language" is even recommended in SIL-0 application, so I do not understand the Non-SIL-4 argument here, can you detail @stefan-karg .

By using a real instead of a well defined unsigned int32 just puts additional strict checks on typing and conversion on the verification list.
Since you do not have an EVC timing conconcpet please reconsider changing from real.

You also deviate from the technical annex of the requirement "1900. logical_voted_time (data flow, cel) = [...]range : 0..2**31 - 1;"

**Comment by JakobGartner** [comment]
Hmm,

SCADE is a formal modelling language in the sense of EN51028, this is also documented in the related certificates that have been issued by several notified bodies, EBA evaluators, foreign certification bodies etc.

The target language has a very limited significance in such a context, which is even more supported by the fact that SCADE KCG generates only what is considered a safe subset of C.
When choosing KCG Ada, it makes use of the very strongly typed features of this language.

As from KCG 6.4, (= the new SCADE language that we don’t yet use), Ada typing concepts have been integrated into the SCADE language itself, as well.
So, I disagree with the statement that “real” means a contradiction to “strongly typed language”, especially as during code generation this “real” is mapped to a well- defined c type. 

Now, if we would wish to use “real” in a real OBU, we would if course have to make sure that the actual implementation is safe (=validated and verified), either by using certified / validated math libs, by replacing calls to a math lib with safe imported operators (probably with validated macros), or, most likely, by using the current model as what it really is: an executable SW spec which serves as input to a full EN51028 SW development process. 

At the beginning of the project we decided that using “real” (with all the question that it may raise further down the V&V / certification process) is a smaller pain that trying to solve the numerical issues that come with integer arithmetics. 
While this is no big problem with T_TRAIN, it brings significant challenges for example at braking curves calculations.

I therefore recommend to stay where we are.


In addition, this (and all other values) are being transported as integer values as long as they are part of messages or packets, we only convert them to “real” as soon as they enter the EVC perimeter itself, in practise directly where they are used. 


If floating point operations would be unsafe per se, all modern airplanes would fallout of the skies immediately. Only trains stay stuck with integers only.

**Comment by MarcBehrens** [comment]
The taget language will come into affect when a transformation from SCADE-API to EVC-API to Air-Gap is considered and there are different types used.

@jacobgartner, do I understand you right that you propose to have a time resolution of lower then 10ms for the EVC timestamp - or does the calculation with real values only apply to internal speed supervision time calculation?

If using real is a design decision it does not need to apply to T_TRAIN.
To which API is the real timestamp compliant?

**Comment by MarcBehrens** [comment]
Please note that the EBA e.g. does not allow to have structured datatypes with real thus choosing real should be well thought of.

**Comment by JakobGartner** [comment]
As I said, at the airgap we use the data type as defined in the SRS 7.5.1.154 (integer with 10ms resolution)

For pragmatic reasons I propose to stay with the real- based data type (resolution 0.01 seconds) inside the model.
As soon as variables cross the EVC boundary they are coded as required  in the SRS. 


I agree that the typing system “i inherited” needs a lot of rework (there are many examples) but if we tackle that all at once we get blocked.

I think that the formalisation of subset 26 chapters 6,7 and 8 that is happening in TrackMessages provides a good basis for this.
At the airgap, we are *much* closer to the SRS than before, with some exceptions (BCD values, NID values where we see bit- position based coding) and some others which will be fixed step by step.

We were blocked for a long time because of this very fundamental work, and I want to avoid new blockages, so this will be fixed at a later point in time and step-by-step. 


Jakob

**Comment by BerndHekele** [comment]
I propose to take this correction to the next iteration (but clean the relevant types.)
I therefore mark this as nextIteration.

**Comment by UweSteinkeFromSiemens** [comment]
Please note that time calculations within the OBU are based upon Obu_BasicTypes_Pkg::T_internal_Type (int with resolution of 1 ms) in general. 
This has to be differentiated from T_TRAIN as defined by the ETCS language (Subset 026-7) and the floating point representation in the test environment. 

The clocking of the model is mainly independant from the time resolution.

**Comment by JakobGartner** [comment]
I agree. 

I will look at the conversion operator in TrackMessages and make sure the time arrives in the right format. 

Jakob

**Comment by stefan-karg** [comment]
Issue closed, since the conversions are used now and we do not face any problems related to T_TRAIN at the moment.
