### ISSUE TITLE
Scade Runtime Error 8

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#532]
We regularly see the error 8 when jumping from production of the build to the simulation of the model.
The error is sporadic in the sense, that not in all situations the error happens.

Cleanup of the production folder in most cases helps.
Reduction of the model helps (especially debug information and optimisation levles).

Sometimes, a restart of the computer is necessary.

In the test-bench a special profile is adjusted for avoiding the scenario (SimuStef).
SimDB is aligned with the settings of the DB licenses.

The issue has been reported to Esterel.

**Comment by UweSteinkeFromSiemens** [comment]
The same error occurs when starting the simulation of https://github.com/openETCS/modeling/blob/master/model/Scade/System/OBU_PreIntegrations/TestBenchExample/TestBenchExample.etp with the simulator of SCADE Suite R16.1b under the following conditions:

- Root operator: TestExample_Pkg::ROOT_Test
- Code Generator: KCG 6.4
- Debug information enabled with "Debug All" set

The error message is : "... TestExample_Pkg_ROOT_Test.dll: Simulator load error: 8

The error is reproducable.

**Comment by janWelte** [comment]
I had the same problems with R16.1a until I took the full track Am-Ut out of the testbench model. 
This seems to be a recurring error under certain condition with large data structures.

For me these problems have been sometimes random, so it would be intersting to know Esterels answer.

**Comment by BenjaminBeichler** [comment]
Can you try the Code-Generation with the Options "Generate context as global" in Configuration and "Local variables as static" in Optimizations ? Both options heavily reduces the needed stack space of the simulator process because data is moved to the data segment. All standard processes have only a stack size of some KB and due to the very deep calling tree of our model, many local variables are allocated on stack and it simply overflows.

I know back in the time of the review, stefan karg and I could solve problems with the old testmodel.

**Comment by JakobGartner** [comment]
Same recommendation



On 7 juil. 2015, at 13:46, Benjamin Beichler <notifications@github.com>
wrote:

Can you try the Code-Generation with the Options "Generate context as
global" in Configuration and "Local variables as static" in Optimizations ?
Both options heavily reduces the needed stack space of the simulator
process because data is moved to the data segment. All standard processes
have only a stack size of some KB and due to the very deep calling tree of
our model, many local variables are allocated on stack and it simply
overflows.

I know back in the time of the review, stefan karg and I could solve
problems with the old testmodel.

—
Reply to this email directly or view it on GitHub
<https://github.com/openETCS/modeling/issues/532#issuecomment-119264868>.

**Comment by UweSteinkeFromSiemens** [comment]
Answer from Esterel Support: 

Cause: Actually the most likely cause of this error is that there is no enough memory to simulate the model:
ERROR_NOT_ENOUGH_MEMORY 8 (0x8) Not enough storage is available to process this command. 

You can find all the error codes from the following link: http://msdn.microsoft.com/en-us/library/ms681382%28v=vs.85%29.aspx 

Resolution:As workaround we recommend to the user to not use the -debug all option in that case. Since SCADE Suite 6.2 we have introduce the possibility to use the option -debug only on part of the model. Indeed in general you only want to debug and have full visibility on part of the model not on the whole system. This is useful to overcome memory issue.Using batch mode could be also helpful as it does not required as memory as the GUI mode.

**Comment by UweSteinkeFromSiemens** [comment]
Setting "Local variables as static" and "Generate context as global" solved the problem for  https://github.com/openETCS/modeling/blob/master/model/Scade/System/OBU_PreIntegrations/TestBenchExample/TestBenchExample.etp .
