### ISSUE TITLE
SpeedSupervision_Integration: syntax error

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#548]
Dear Thorsten,
the model has still an syntax error.
Can you please correct:

(0) : error ERRSEM_VAR_NOT_DEC : Variable MRSPMaxSections : variable not declared

kind regards
Bernd

**Comment by T12z** [comment]
(Sorry for not being present this morning. I had to participate a stirring external appointment)

As I complained earlier in #513 and the blamed change 9d7fb06 I suspect this error to be inherrited from TrackAtlas package. That package is in a really sub-par state currently as it throws a few errors when opening and more when checked -- Too many for a non-maintainer-fix, sorry.

Wasn't there a new relase planned for this pkg?

**Comment by BerndHekele** [comment]
I hope we are approaching a more stable view on this component now.

**Comment by JakobGartner** [comment]
TrackAtlas has been totally reworked and is in final internal tests before a 1st working status release which I hope to do this evening.


As for this error, it can only be a path wrongly set in SpeedSupervision 

The constant has the path TrackAtlasTypes::MRSPMaxSections (as it has since the beginning)

**Comment by T12z** [comment]
... eagerly hanging out for that release ;)

Paths in SpeedSupervision have all been fixed. The error is already thrown when opening TrackAtlas.etp - which is the deprecated version from github.

**Comment by BerndHekele** [comment]
Solution available.
