### ISSUE TITLE
TM::Read_P131 requires Packet_Types_Pkg::P131_RBCTransitionOrder_T as output type

### ISSUE THREAD

**Issue by UweSteinkeFromSiemens** [openETCS/modeling#554]
... instead of TM::P131_OBU_T. 

By the way, P131_OBU_T lacks of the q_scale field.

**Comment by JakobGartner** [comment]
This is not a bug, all packets were redefined in order to be closer to the SRS.
(even if this one is identical)

A function has been added for your convenience: TM_specific::Read_P131_Legacy.

**Comment by JakobGartner** [comment]
and yes, the Q_SCALE bug was a bug, which is now fixed

**Comment by UweSteinkeFromSiemens** [comment]
Hmm, Packet_Types_Pkg::P131_RBCTransitionOrder_T has been defined antecedently. Why 2 type definitions for the same structure?

**Comment by JakobGartner** [comment]
The transport mechanism (= model TrackMessages) has been fundamentally changed.
- Input and output from/ to the track SRS conformal (in structure and content)
- Systematic treatment of different baselines
- Modular library using the same pack/ unpack algorithms for all packets 

In principle the library is now layered according to the OSI model.

The originally designed data types do not share the same structure across all the different components, that's why ALL packets and messages have new representations from TrackMessages point of view.

You can either use this types directly or request a conversion function to your preferred format.
For P131(and other types that have no N_ITER)  this is not very interesting as they are identical.

**Comment by JakobGartner** [comment]
@UweSteinkeFromSiemens 
if this works, please close the issue

**Comment by UweSteinkeFromSiemens** [comment]
I'm using TM::Read_P131 now.
