### ISSUE TITLE
DMI: Safe radio connection is indicated too early

### ISSUE THREAD

**Issue by stefan-karg** [openETCS/modeling#595]
The indicator for the safe radio connection is displayed directly after the train wakes up. At this point of time, the registration of the mobiles is triggered, but the safe radio connection is established later. 

In our scenario, this happens after overpassing the BG 352 and 353. Then the safe radio connection should be indicated.

As discussed, most probably, the DMI is connected to the wrong output of the MoRC module.

**Comment by BerndHekele** [comment]
I checked the outputs - they are ok.
The safe state is indicated before the session is available.
We need to check with the standard what the correct behaviour is.

**Comment by BaseliyosJacob** [comment]
Dear Bernd and Stefan,

the safe  radio connection should be displayed as soon as the safet radio connectin is established and not before. I have check the standalone DMI an the connection is not displayed since API_RadioConnection_Pkg::conn_unknown is setted.

**Comment by BaseliyosJacob** [comment]
![image](https://cloud.githubusercontent.com/assets/3975810/8834012/257e068c-30b2-11e5-8731-0954f006ef7b.png)

**Comment by BaseliyosJacob** [comment]
The status is changing to connected as soon API_RadioCommunication_Pkg::conn_ConnectionUp is setted.

![image](https://cloud.githubusercontent.com/assets/3975810/8834082/84f99522-30b2-11e5-9b10-59217957fd89.png)

**Comment by BerndHekele** [comment]
The question is:   
- is this state related to a connection of the train to a concrete RBC after having exchanged the messages (my understanding)
- or is this state related to the capability of the mobile to connect (current setting by the MoRC.
@UweSteinkeFromSiemens

**Comment by UweSteinkeFromSiemens** [comment]
MoRC provides an output "safeRadioConnectionStatus_toDriver" signaling the safe radio connection status. MoRC extracts that from the mobile connection status, which does not seem to be correct, because:

My current state of knowledge is, that the safety layer resides on top of the mobiles GSM protocol stack and outside the OBU application. Therefore, the safety layer is not part of MoRC itself, but MoRC has to indicate its status. Confusing, really ...

**Comment by BerndHekele** [comment]
This statement give some light on the topic.
We can simulate this hw-behaviour in the environment.

Thanks. for the update.

**Comment by stefan-karg** [comment]
Dear Uwe,

the mobile is simulated in the environment simulation using a state machine. Once the mobile gets the request to register, it will register itself (using some cycles of delay). 

I now saw in the MoRC module, that the safe connection is indicated, once the mobile is registered and the SW status is changed to *mswc_registered*, see the screenshot: (Operator managementOfRadioCommunication)

![morc_register](https://cloud.githubusercontent.com/assets/1040937/8850406/259a948c-3148-11e5-8eed-098699be3224.png)

From my understanding, the safe radio connection should not be indicated at the registration of the mobiles but after establishing the connection.

While investigating this issue, I found also, that the statemachine located at *MoRC_Pck::Subfunc_Pkg::radioNetworkMobile/MobileHW_available_SM:MobileHWAvailable* is only triggered until the state "registered".

Do we maybe still not trigger the inputs to the MoRC module correctly?

**Comment by UweSteinkeFromSiemens** [comment]
Dear Stefan, 
this is what I meant with my comment to this issue this morning (see above). 
If replacing mswc_registered by mswc_connected helps you, I can modify the model. 

But mswc_connected might also be wrong, since registering (for the radio network) and connecting (calling the RBCs phone number) reside on GSM layer. Establishing and terminating address the session layer, maintained by MoRC. In between, the safety layer provides the safe connection. 

Since the safety layer is not explicitly covered by the session management nor by RBC handover procedure or the ETCS language, it seems to be a somewhat hidden component outside the OBU. 

I will start reengineering MoRC next week and analyze this problem. For the time beeing, please don't wonder to much about MoRC as it is now.

**Comment by stefan-karg** [comment]
A temporary workaround is currently used. The actual issue will be fixed once the updated implementation of MoRC is available.

**Comment by UweSteinkeFromSiemens** [comment]
@stefan-karg : Please check, if the bug is fixed by MoRC_HO now.

**Comment by stefan-karg** [comment]
This is fixed now.
