### ISSUE TITLE
ProvidePositionReport and Request_MA send messages even without radio-connection

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#613]
I recognised both models do not care about the situation of the radio connection.
They send messages before a connection is possible resp. before they are suppost to.

How shall we handle this in long term?
Is this a task of the famous radio management or is each function responsible for taking ccare of the status of the train?

kr.
Bernd

**Comment by christianstahl** [comment]
I would not like to add the same functionality (i.e. checking the connection) to several modules, and therefere feel more comfortable with shifting this check to the radio management.

**Comment by UweSteinkeFromSiemens** [comment]
The radio management provides the status of the connection. 
But is would be inappropriate, if it comprises all the knowledge of other subfunctions, how to handle dependancies of the radio connection.

**Comment by JakobGartner** [comment]
It would be important to understand how these issues are synchronised/ handled.

- Every local function "knows" the status of the radio connection (and other factors) and sends messages only when appropriate 
- The messages are sent anyway but will only be sent via radio when there is a connection and they are "not too old", possibly with a feedback to the sender that they could not be sent?

I think it os probably a mix, but I don't yet have a deeper understanding of the issue.

We should also consider that there could be several radio modems?
Are there similar conditions for all TrainToTrack messages whether they shall be sent?
Do the functions that need to send messages care whether they could send?


Maybe it could be a solution that the upcoming TrainToTrack message bus that we discussed handles the different situations transparently (accepts messages only under the "legal" conditions?

**Comment by UweSteinkeFromSiemens** [comment]
As I know so far, only the RBC handover procedure and the InformationFilter need to handle the 2 radio modems and radio sessions that may be in operation concurrently. Hereby, the InformationFilter filters the received messages from both mobiles, while RBCHandover and MoRC control the mobiles and the routing of the output data stream to the mobiles.

**Comment by BaseliyosJacob** [comment]
Dear all,

as Uwe already described:

We should also consider that there could be several radio modems?

This is just the Case when we have a RBC- RBC Handover.

 Are there similar conditions for all TrainToTrack messages whether they shall be sent?

Not in the current case.

 Do the functions that need to send messages care whether they could send?
From my point of view no. But the Procedure in the OBU and RBC should take care whether they are should computed or rejected.

e.g. sending of MA request after receving of MA. In this case the MA request will be not considered since the MA procedure did finisch for this section.

**Comment by BerndHekele** [comment]
Done.
