### ISSUE TITLE
Packet with nid_packet = -1 marked as valid

### ISSUE THREAD

**Issue by stefan-karg** [openETCS/modeling#615]
The general message (NID_MESSAGE = 24), which is sent during User story 7 and contains the packets 57 and 58 contains after the two packets a third packet with NID_PACKET = -1, which is marked as valid.

This leads to a consistency error in the check, since a packet with NID_PACKET = -1 does not exist.

The trigger-ID of the message is 353004310 (see XREF-file).

**Comment by JakobGartner** [comment]
The messages 24 are not sent from the track model, but dynamically generated inside the RBC model

**Comment by stefan-karg** [comment]
This particular message 24 is triggered by the RBC but created by the track model, since it contains additional packets.

After having a closer look, it seems to be a general problem with processing the packet 255 (End of Information). In the packet data, the NID_PACKET is correctly specified as 255, while the header (= the metadata field) contains a -1, which converts to 0 when I use the TM::T_extract_nid_packet_from_metadata_selector operator to get the NID_PACKET. NID_PACKET = 0 would be a Virtual Balise Cover, but not End of Information.

@JakobGartner

**Comment by JakobGartner** [comment]
ok,

I will check and correct.

-1 is normally issued on non-valid messages

**Comment by JakobGartner** [comment]
This has been corrected.
Each Send Packet operator has a check that sets the NID-PACKET to -1 if the expected NID_PACKET does not equal the data in the packet actually sent.
The error detection function in the variable translation function not yet being implemented, this leads to erroneous behaviour.
As a residual copy and paste leftover, the expected NID_PACKET in Send_P255 had been left at 1 so that the metadata contained the -1....

Now corrected ,

**Comment by stefan-karg** [comment]
Correction is working.
