### ISSUE TITLE
InformationFilter: some table elements not according to SRS

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#637]
Some descision tables need correction.

**Comment by ShuangjiaoCao** [comment]
## General remark:
InformationFilter: some table elements not according to SRS 



## Review 
InformationFilter: table elements  from https://github.com/openETCS/modeling/tree/master/model/Scade/System/ObuFunctions/ManageLocationRelatedInformation/BaliseGroup/InformationFilter


#####  1. DataDictionary_Pkg->Constants->LevelDecisionTableFromBalise:


Reference document:
  *  SUBSET-026-4, Chapter 4.8.3
  *  Table §4.8.3 from §4.8.3 & § 4.8.4.xlsx  under https://github.com/openETCS/modeling/tree/master/openETCS%20ArchitectureAndDesign/Work%20Groups/Group%202/Filtering%20Track%20Information 

Nr.12:  Both *Signalling Related Speed Restriction* and *Movement Authority* are from Packet 12. The table only stored the value of *Movement Authority*

Nr.49: Both *List of Balises for SH area* and *List of Balises in SR mode* are from Packet 49. The table only stored the value of  *List of Balises for SH area*.

Error in Nr.65: *Temporary Speed Restriction* not with value [LD_Accept, LD_0102StoreIfPendingLevelTransition, LD_Accept, LD_Accept, LD_Accept]
but [LD_Accept, LD_0102StoreIfPendingLevelTransition, LD_Accept, LD_08InhibitionOfRevocableTSR, LD_08InhibitionOfRevocableTSR]

Nr.42:  Both *Session Management with neighbouring RIU* and *Session Management * are from Packet 42. The table only stored the value of  *Session Management*

Error in Nr.90: *Track Ahead Free up to level 2/3 transition location* not with value [LD_09RejectIfNoL2L3TransitionStored, LD_09RejectIfNoL2L3TransitionStored, LD_09RejectIfNoL2L3TransitionStored, LD_09RejectIfNoL2L3TransitionStored, LD_09RejectIfNoL2L3TransitionStored]
but [LD_09RejectIfNoL2L3TransitionStored, LD_09RejectIfNoL2L3TransitionStored, LD_09RejectIfNoL2L3TransitionStored, LD_Reject, LD_Reject]


#####  2. DataDictionary_Pkg->Constants->LevelDecisionTableFromRBC:

 Reference document:
  *  SUBSET-026-4, Chapter 4.8.3
  *  Table §4.8.3 from §4.8.3 & § 4.8.4.xlsx  under https://github.com/openETCS/modeling/tree/master/openETCS%20ArchitectureAndDesign/Work%20Groups/Group%202/Filtering%20Track%20Information 

Nr.12:  Both *Signalling Related Speed Restriction* and *Movement Authority* are from Packet 12. The table only stored the value of *Movement Authority*.

Nr.49: Both* List of Balises for SH area* and* List of Balises in SR mode* are from Packet 49. The table only stored the value of  *List of Balises for SH area*.

Nr.42:  Both *Session Management with neighbouring RIU* and *Session Management * are from Packet 42. The table only stored the value of  *Session Management*.

Error in Nr. 68: *Track Conditions excluding big metal masses* not with value [LD_Invalid, LD_Invalid, LD_Invalid, LD_Invalid, LD_Invalid]
but [LD_02StoreIfPendingL2L3Transition, LD_02StoreIfPendingL2L3Transition, LD_02StoreIfPendingL2L3Transition, LD_03RejectIfPendingAckOfTrainData, LD_03RejectIfPendingAckOfTrainData]

Error in Nr. 40: * Train Runnng Number(Train to track in Packet 40)* not with[LD_Invalid, LD_Invalid, LD_Invalid, LD_Invalid, LD_Invalid]
but [LD_Reject, LD_Reject, LD_Reject, LD_Accept, LD_Accept]

Error in Nr. 0: *Virtual Balise Cover order(in Packet 6/0)* not with value
[LD_02StoreIfPendingL2L3Transition, LD_02StoreIfPendingL2L3Transition, LD_02StoreIfPendingL2L3Transition, LD_Invalid, LD_Invalid] but [LD_Invalid, LD_Invalid, LD_Invalid, LD_Invalid, LD_Invalid]





#####  3. DataDictionary_Pkg->Constants->ModeDecisionTable:
Reference document:
  * SUBSET-026-4, Chapter 4.8.4
  * Table §4.8.4 from §4.8.3 & § 4.8.4.xlsx  under https://github.com/openETCS/modeling/tree/master/openETCS%20ArchitectureAndDesign/Work%20Groups/Group%202/Filtering%20Track%20Information 

Error in Nr. 45: *Radio Network registration*(because of the mistake of table §4.8.4 Nr.15. Packet 45 not 49) not empty but with value [MD_NotRelevant, MD_02IfCabActive, MD_Accept, MD_Accept, MD_Accept, MD_Accept, MD_Accept, MD_Accept, MD_Accept, MD_Accept, MD_Accept, MD_Accept, MD_01IfFollowingExitTRMode, MD_NotRelevant, MD_NotRelevant, MD_Accept, MD_Accept]

Error in Nr. 57: *MA Request Parameters* not with value
[MD_NotRelevant, MD_02IfCabActive, MD_Reject, MD_Reject, MD_Accept, MD_Accept, MD_Accept, MD_Accept, MD_Reject, MD_Accept, MD_Accept, MD_Reject, MD_01IfFollowingExitTRMode, MD_NotRelevant, MD_NotRelevant, MD_Accept, MD_Reject] but[MD_NotRelevant, MD_02IfCabActive, MD_Reject, MD_Reject, MD_Accept, MD_Accept, MD_Accept, MD_Accept, MD_Reject, MD_Reject, MD_Accept, MD_Reject, MD_01IfFollowingExitTRMode, MD_NotRelevant, MD_NotRelevant, MD_Accept, MD_Reject]

Error in Nr. 13: *SR distance information from loop* not empty but with value[MD_NotRelevant, MD_Reject, MD_Reject, MD_Reject, MD_Reject, MD_Reject,MD_06RejectIfOverrideActive, MD_Reject, MD_Reject, MD_Reject, MD_Reject, MD_Reject, MD_Reject, MD_NotRelevant, MD_NotRelevant, MD_Reject, MD_Reject]


Nr.49: Both* List of Balises for SH area* and *List of Balises in SR mode* are from Packet 49. The table only stored the value of  *List of Balises for SH area*.


Nr.42:  Both* Session Management with neighbouring RIU* and *Session Management * are from Packet 42. The table only stored the value of  *Session Management*

Nr.39,68:  Both *Track conditions excluding sound horn, non stopping areas, tunnel stopping areas and big metal masses* and *Track conditions sound horn, non stopping areas, tunnel stopping areas* are from Packet 39 and 68. The table only stored the value of   *Track conditions excluding sound horn, non stopping areas, tunnel stopping areas and big metal masses*.


Nr.80:   *Mode Profile* used twice in xlsx table §4.8.4 Number 46 and Number 5 

Nr.49: * List of Balises for SH area* used twice in xlsx table §4.8.4 Number 47 and Number 6 




Error in Nr. 40: *Train Running Number(Packet 40 Train to Track)* not empty but with value[MD_NotRelevant, MD_02IfCabActive, MD_Reject, MD_Reject, MD_Accept,  MD_Accept, MD_Accept, MD_Accept, MD_Reject,  MD_Accept, MD_Reject,  MD_Accept, MD_Accept, MD_NotRelevant, MD_NotRelevant, MD_Reject,  MD_Accept]


#####  4. Errors in  §4.8.3 of  xlsx-file under https://github.com/openETCS/modeling/tree/master/openETCS%20ArchitectureAndDesign/Work%20Groups/Group%202/Filtering%20Track%20Information 


Nr.17   Package 63:   here not  Package 63 but Packet 63
Nr.22   Package 64:   here not  Package 64 but Packet 64
Nr.31   Package 135:   here not  Package 135 but Packet 135

Nr.33   Package 42:   here not  Package 42 but Packet 42
Nr.63   Package 52:   here not  Package 52 but Packet 52
Nr.64   Package 88:   here not  Package 88 but Packet 88
Nr.65   Package 6(0):   here not  Package  6(0) but Packet 6(0)
Nr.66   Package 44:   here not  Package 44 but Packet 44

#####  5.  Errors in  §4.8.4 of xlsx-file under  https://github.com/openETCS/modeling/tree/master/openETCS%20ArchitectureAndDesign/Work%20Groups/Group%202/Filtering%20Track%20Information 




Nr.11, Nr.12:  empty
Nr.15   Packet 49:   here not  Packet 49 but  Packet 45
Nr.24   Package 64:   here not  Package 64 but Packet 64
Nr.33   Package 135:   here not  Package 135 but Packet 135
Nr.34   Package 133:   here not  Package 133 but Packet  133
Nr.35   Package 42:   here not  Package 42 but Packet 42
Nr.36   Package 134:   here not  Package 134 but Packet 134
Nr.38   Package 136:   here not  Package 136 but Packet  136
Nr.67   Package 52:   here not  Package 52 but Packet 52
Nr.68   Package 88:   here not  Package 88 but Packet 88
Nr.69   Package 6(0):   here not  Package 6(0) but Packet 6(0)
Nr.70   Package 44:   here not  Package 44 but Packet 44

**Comment by UweSteinkeFromSiemens** [comment]
Does the InformationFilter match #430 ?

**Comment by BerndHekele** [comment]
No longer relevant
