### ISSUE TITLE
Balise 354 packet 46 (Conditional level transition)

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#644]
In this packet the priority is on level ntc.
This cannot trigger a level change to level 2.
Is this behaviour in proper operation of the track correct (no test operation?

**Comment by JakobGartner** [comment]
The packets in BG354 contain (JRU)



NID_PACKET(8bits) = Conditional Level Transition Order(46)
Q_DIR(2bits) = Nominal(1)
L_PACKET(13bits) = 42bits(42)
M_LEVELTR(3bits) = Level STM(1)
    NID_STM(8bits) = ATB
N_ITER(5bits) = 1(1)
    1: M_LEVELTR[1](3bits) = Level 2(3)”




NID_PACKET(8bits) = Conditional Level Transition Order(46)
Q_DIR(2bits) = Reverse(0)
L_PACKET(13bits) = 39bits(39)
M_LEVELTR(3bits) = Level STM(1)
    NID_STM(8bits) = ATB
N_ITER(5bits) = 0(0)"


Then, the RBC message at LRBG 354 

NID_PACKET(8bits) = Level Transition Order(41)
Q_DIR(2bits) = Nominal(1)
L_PACKET(13bits) = 89bits(89)
Q_SCALE(2bits) = 1m(1)
D_LEVELTR(15bits) = 801.0m(801)
M_LEVELTR(3bits) = Level 2(3)
L_ACKLEVELTR(15bits) = 210.0m(210)
N_ITER(5bits) = 1(1)
    1: M_LEVELTR[1](3bits) = Level STM(1)
            NID_STM[1](8bits) = ATB
        L_ACKLEVELTR[1](15bits) = 210.0m(210)"

This has been reflected in the track model

Later we see in the JRU data the following position reports:

NID_PACKET(8bits) = Position Report(0)
L_PACKET(13bits) = 122bits(122)
Q_SCALE(2bits) = 10cm(0)
NID_C(10bits) = 426
NID_BG(14bits) = 354(354)
D_LRBG(15bits) = 800.8m(8008)
Q_DIRLRBG(2bits) = Nominal(1)
Q_DLRBG(2bits) = Nominal(1)
L_DOUBTOVER(15bits) = 20.8m(208)
L_DOUBTUNDER(15bits) = 21.0m(210)
Q_LENGTH(2bits) = No train integrity information available(0)
V_TRAIN(7bits) = 90km/h(18)
Q_DIRTRAIN(2bits) = Nominal(1)
M_MODE(4bits) = STM National(13)
M_LEVEL(3bits) = Level STM(1)
    NID_STM(8bits) = ATB

NID_PACKET(8bits) = Position Report(0)
L_PACKET(13bits) = 114bits(114)
Q_SCALE(2bits) = 10cm(0)
NID_C(10bits) = 426
NID_BG(14bits) = 354(354)
D_LRBG(15bits) = 808.3m(8083)
Q_DIRLRBG(2bits) = Nominal(1)
Q_DLRBG(2bits) = Nominal(1)
L_DOUBTOVER(15bits) = 20.9m(209)
L_DOUBTUNDER(15bits) = 21.1m(211)
Q_LENGTH(2bits) = No train integrity information available(0)
V_TRAIN(7bits) = 90km/h(18)
Q_DIRTRAIN(2bits) = Nominal(1)
M_MODE(4bits) = Full Supervision(0)
M_LEVEL(3bits) = Level 2(3)"

**Comment by JakobGartner** [comment]
(sorry, resent due to mingled copy/ paste effects)

The packets in BG354 contain (JRU)

NID_PACKET(8bits) = Conditional Level Transition Order(46)
Q_DIR(2bits) = Nominal(1)
L_PACKET(13bits) = 42bits(42)
M_LEVELTR(3bits) = Level STM(1)
    NID_STM(8bits) = ATB
N_ITER(5bits) = 1(1)
    1: M_LEVELTR[1](3bits) = Level 2(3)"
NID_PACKET(8bits) = Conditional Level Transition Order(46)
Q_DIR(2bits) = Reverse(0)
L_PACKET(13bits) = 39bits(39)
M_LEVELTR(3bits) = Level STM(1)
    NID_STM(8bits) = ATB
N_ITER(5bits) = 0(0)"



Then, the RBC message at LRBG 354 

NID_PACKET(8bits) = Level Transition Order(41)
Q_DIR(2bits) = Nominal(1)
L_PACKET(13bits) = 89bits(89)
Q_SCALE(2bits) = 1m(1)
D_LEVELTR(15bits) = 801.0m(801)
M_LEVELTR(3bits) = Level 2(3)
L_ACKLEVELTR(15bits) = 210.0m(210)
N_ITER(5bits) = 1(1)
    1: M_LEVELTR[1](3bits) = Level STM(1)
            NID_STM[1](8bits) = ATB
        L_ACKLEVELTR[1](15bits) = 210.0m(210)"

This has been reflected in the track model

Later we see in the JRU data the following position reports:

NID_PACKET(8bits) = Position Report(0)
L_PACKET(13bits) = 122bits(122)
Q_SCALE(2bits) = 10cm(0)
NID_C(10bits) = 426
NID_BG(14bits) = 354(354)
D_LRBG(15bits) = 800.8m(8008)
Q_DIRLRBG(2bits) = Nominal(1)
Q_DLRBG(2bits) = Nominal(1)
L_DOUBTOVER(15bits) = 20.8m(208)
L_DOUBTUNDER(15bits) = 21.0m(210)
Q_LENGTH(2bits) = No train integrity information available(0)
V_TRAIN(7bits) = 90km/h(18)
Q_DIRTRAIN(2bits) = Nominal(1)
M_MODE(4bits) = STM National(13)
M_LEVEL(3bits) = Level STM(1)
    NID_STM(8bits) = ATB

NID_PACKET(8bits) = Position Report(0)
L_PACKET(13bits) = 114bits(114)
Q_SCALE(2bits) = 10cm(0)
NID_C(10bits) = 426
NID_BG(14bits) = 354(354)
D_LRBG(15bits) = 808.3m(8083)
Q_DIRLRBG(2bits) = Nominal(1)
Q_DLRBG(2bits) = Nominal(1)
L_DOUBTOVER(15bits) = 20.9m(209)
L_DOUBTUNDER(15bits) = 21.1m(211)
Q_LENGTH(2bits) = No train integrity information available(0)
V_TRAIN(7bits) = 90km/h(18)
Q_DIRTRAIN(2bits) = Nominal(1)
M_MODE(4bits) = Full Supervision(0)
M_LEVEL(3bits) = Level 2(3)"

**Comment by BerndHekele** [comment]
Done.
