### ISSUE TITLE
TM:TM_specific::Read_P015_Legacy does not read P15

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#650]
Even though the packet in the track message is valid the procedure does not give the output.

**Comment by JakobGartner** [comment]
Yes, i can reproduce.

There is a small error with big effect in the logic to map the “start section + N_ITER sections” from the SRS to the “N_ITER + 1” sections in the old type definition. 
Am a bit too tired to fix it right away, will do first thing tomorrow.

**Comment by JakobGartner** [comment]
done.

**Comment by BerndHekele** [comment]
This one works now. Thanks.
P21 and P27 have  similar problem.
Can you please correct them as well?

**Comment by JakobGartner** [comment]
Hello Bernd,

I think that P21 is working, at least on my test example.



The only regular consumer of P21 is TrackAtlas, and here I do not use those types that are too far from the SRS.



Marielle only needs the valid flag of the 1st section, as far as I see, am I wrong?


And, do you use the outputs from TrackAtlas or do you build new interface?


Similar for P27:
Marielle only needs the valid flag. The conversion operator gives nothing than that (to convert P27 is a bit more work thanks to its 2 layers of iterations, so if there is no use case, I prefer not to do it)

**Comment by BerndHekele** [comment]
P21 and P27 are in the current interface to M&L. For both the information as such is not needed for M&L.
But, we have an existing implementation.

In the current implementation I still directly feed Mode and Level from the EVC model. I do not change thi due to:
 - having more flexibility in testing the reaction
 - having a solution available without additiopnal effort (besides checking the convertion routines.

You did not cancel the P21 and P27 specific routines - so, they should be working.

It is probably easier to correct them compared to faking the data on my side.

**Comment by JakobGartner** [comment]
In the TrackAtlas to M&L interface, you find 1:1 connections to the relevant operators in M&L's "input management", including P21 and P27. You have the choice to use the high-level connector to "Input_MA_SSP_Gradien" and/ or the connector "InputTrackManagement". 
I have rebuilt the interface so that I can be connected without implying Marielle while she is not available. 

Well I am surprised that P21 should not be working, at least in my test case, it does.
![screen shot 2015-08-12 at 11 06 58](https://cloud.githubusercontent.com/assets/8400941/9220377/7f9d8fc6-40e2-11e5-9ad7-8989b70b6aa0.png)

What is the specific problem?

For P27 I have built a very simple extractor.
While Marielle is interfacing the full P27, she is really only using the valid flag. 
That's also all she gets.

**Comment by JakobGartner** [comment]
and yes, of course you can also use them to shortcut the connection to M&L---

**Comment by BerndHekele** [comment]
As soon as I have corrected the level change I will switch to use the trackatlas Infromation for M&L as well. Promissed.

**Comment by BerndHekele** [comment]
I close this issue since it is no longer relevant (different access to the track atlas in use.)
