### ISSUE TITLE
TrackAtlas - SDM Interface not aligned

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#680]
Dear Partner,
I get an ERR_100 from the SDM Input Wrapper.caused by changes in the TrackAtlas-Types.
This is not expected in this phase and blocking proress.

Please correct.

kr
Bernd

**Comment by T12z** [comment]
About "if it were correctly implemented", I oppose to that:
Since the breaking data type is a **dedicated** message to SDM, it is consumed completely by flattening. If it breaks, due to new message parts, it also means I would have to implement the new data in some way or another. So it I'd say implementation is correct, but the update should be done in a more sensitive way - which it will, all good, :sunny:
