### ISSUE TITLE
SpeedMonitoring: Speed Limited to 1.98 km/h

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#683]
When starting the train the speed with the new profile for ntc the speed is limited to 1.98 km/h.
The test can be started easily.
Please contact me for further details.

kr
Bernd

**Comment by BerndHekele** [comment]
Analysis result: data to supervision from TrackAtlas not correct.
Sorry for the confusion.

kr
Bernd

**Comment by JakobGartner** [comment]
done

**Comment by BerndHekele** [comment]
Dear Jakob,
fix does not work - sorry.
Still  no data at the correct output.

Bernd

**Comment by BerndHekele** [comment]
Having a second look it works.
thanks.
Looked weird.

**Comment by stefan-karg** [comment]
Dear Jakob,

probably due to the corrections of the type errors yesterday evening, the constants in the TrackAtlas were reset to default values.

This leads again to the behavior of a train driving with a speed limit of 2 km/h.

**Comment by JakobGartner** [comment]
it s in total renovation anyway

what was now the idea for NTC mode?

should TracAtlas output a speed or will it be isolated outside ?

**Comment by stefan-karg** [comment]
Further analysis shows that it seems to be a problem with the activation of the track atlas in level NTC. The constants were not changed. We are investigating the problem and will provide feedback as soon as we made some progress.

**Comment by JakobGartner** [comment]
At the moment, all constants except the To Supervision are “empty” in NTC.
And the To Supervision is only seeing MRSP to 140km/h * 32km distance——

If you need other values I need to know.

**Comment by T12z** [comment]
would be really sweet to get a valid MA ... though I haven't investigated deeply

**Comment by JakobGartner** [comment]
MA in NTC is not possible, nominally….

**Comment by stefan-karg** [comment]
For not braking us in level NTC you need once the flag freshMRSP, right? @T12z

**Comment by JakobGartner** [comment]
yes I have thought of that too…. it’s in the next release

**Comment by T12z** [comment]
elaborated: I had a discussion with Benjamin about this, we cannot distiguish between, the "do-what-you-like"-NULL-MA and an MA we have just passed and though thrown it away, so we'd always have to brake. Interestingly it looks like this is not always happening, so that is actually a bug in SDM.

Again, from my understanding: no MA == no ride

**Comment by T12z** [comment]
If this is too crude for TA, then SDM needs to be shortcut or silenced some other way

**Comment by JakobGartner** [comment]
Looking from a bit more far I start to believe that deactivating TrackAtlas in NTC is not the right way.
SDM  should probably also be deactivated? 

Of course I can fake an MA with same EOA as the MRSP length by providing the related constant value

**Comment by stefan-karg** [comment]
We were now able to fix the TrackAtlas in a way that we are able to drive until the level transition.

The problem was the activation of the TrackAtlas in mode NTC. The TrackAtlas is surrounded by a boolean activation operator, which in the current version gets activated, if the EVC is in mode NTC. In any other case, the EVC will get the default values for level NTC at the moment.

After inverting this activation (means the TrackAtlas is activated if the mode != NTC), we are able to drive again on the track.

**Comment by JakobGartner** [comment]
Oh 

what a stupid bug (but it comes from the prior solution which replaced the MRSP output when NTC was active)

did you change anything else?

If not, I will just correct this error for my next push, too so that when I overwrite the current model the behaviour will be as expected

**Comment by stefan-karg** [comment]
That solution works, it was the only modification for the moment.

**Comment by JakobGartner** [comment]
OK, thanks

i found a more fundamental issue (about handling of Messages for “future, current and past” LRBGs which prevents correct Gradient Profile and MRSP calculations in some cases when the LRBG changes.
So when you are in Level 2, the behaviour will be wrong.

I am analysing/ fixing this and am sure it will be ok before monday morning.

J

**Comment by BerndHekele** [comment]
We have a running solution for this issue. I close it.
