### ISSUE TITLE
Levels::Request to Ack Level transition is sent twice.

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#693]
I worked on this before.
I thought it is fixed but obvesiouly it is not,

I will provide a proposal soon.

**Comment by BerndHekele** [comment]
Proposed Solution in test

**Comment by BaseliyosJacob** [comment]
Dear Bernd,

there was an issue on the DMI as well due to the ack requested twice.I fixed it on the dmi. May the issue was on DMI side?

**Comment by BerndHekele** [comment]
Hi Baseliyos,
this issue 693 is definitely related to Levels.
I have a correction in test and will push it as soon as I see where the "ignoring the end of the ack-window error" is located.

We have an additional issue related to the DMI: I do not know how to switch the DMI text message off ones we passed that window. This issue is important to be solved for demonstrations.

cu
Bernd

**Comment by BaseliyosJacob** [comment]
Hello Bernd,

can i check it in the current implementation model?

**Comment by BaseliyosJacob** [comment]
Bernd, do you mean switch of the DMI text message after acknowledgement? I doesnt disappear?

**Comment by BaseliyosJacob** [comment]
@BerndHekele @MariellePetitDoche now if could see it in the simulation.

The Ack is sent twice because

- first time triggered by the radio message
- second time triggered by the balise message

the trigger by the balise trigger is just repeating the level transition for the case that the transition has not been triggeres by the RBC message or for level 1 But should be not considered since the first from the RBC has been accepted.

@MariellePetitDoche are you aware of such an issue? The Packet 41 will be once triggered by radio message and in the next balise as well. As mentioned the balise is repeating the packet 41 from the radio message for the case that the radio message has not been considered or Level 1. Can you handle such a event in the mode and level management model?

**Comment by MariellePetitDoche** [comment]
As we have discussed several time, it shall be clearly  define somewhere which information is provided by which and with which meaning: 
Is the information provided in a raw way : all information is transmitted, just when it occurred, and each function shall do is own checking, filtering and storage ? Maybe with several times the same type of computation...
Or is an input function which provide the common information to all other functions, already checked, filtered and memorized, and ready to use ?


this is really  important to know to  properly  define the behavior of the function. The initial description of the function has been made according the second assumption, but some change have been made on some inputs, and for the moment I have no idea how it works.

**Comment by BaseliyosJacob** [comment]
@MariellePetitDoche do have now a better overview since the discussion with Jakob Gärtner yesterday? I have checked the Filter of Package 41 by the filter - but the filter will not reject a package 41 if it is a repetition. Therefore this may should handled in the Mode and Level Management. What do you think?

**Comment by MariellePetitDoche** [comment]
I'am waiting a feedback from Jacob to know where the information I need is available in the Scade model.

**Comment by BerndHekele** [comment]
I close this issue. Solution is available in the current implementation.
