### ISSUE TITLE
S026_7.etp: T_TRAIN must be integer

### ISSUE THREAD

**Issue by UweSteinkeFromSiemens** [openETCS/modeling#719]
T_Train is currently defined as real, must be int. 

Ref: #397, #519.

**Comment by T12z** [comment]
even if not directly related, but there is more:
As me ("SDM") is the only one consuming the other real types of S026_7:
 - A_NVMAXREDADH..
 - A_NVP..
 - M_NVAVADH
 - M_NVK[R,T,V]INT

they all have a very distinct fixed-point description and are not directly involved in complex math, they could be left in original packet representation. As a matter of awkward fact, A_NVP.. is actually converted back to int-fixed-point internally in SDM, because the related calculations are done in integer. :confused:

**Comment by UweSteinkeFromSiemens** [comment]
Done.
