### ISSUE TITLE
Use Case 16: Behavior of the OBU after a TRIP. 

### ISSUE THREAD

**Issue by BaseliyosJacob** [openETCS/modeling#73]
Behavior of the OBU after a TRIP.

The scenario starts after the train has tripped, e.g. by moving past the EoA 
of a given MA. In the diagram above the MA was given to Signal Marker Board 100 and the 
train has moved beyond Signal Marker Board 100.

This should be part of the modelling scope of WP 3.

**Comment by vgontier** [comment]
"Speed and distance monitoring" shall detect the overpassing of the EOA, command the emergency brake and inform "modes and level management".
Therfore, we send to you an "EOA overpassing" data.
Benjamin, Marielle, do you agree ?

**Comment by BenjaminBeichler** [comment]
I would propose a boolean signal as an output of SaDM or do we need more
information?

Véronique Gontier <notifications@github.com> schrieb am Mi., 7. Jan. 2015
15:46:

**Comment by MariellePetitDoche** [comment]
Boolean is sufficient for me.

**Comment by BaseliyosJacob** [comment]
Dear all,

find the Sequence Diagramm and Description for this US on:

https://github.com/openETCS/modeling/blob/master/User%20Stories/User%20Story%2016.pdf

https://github.com/openETCS/modeling/blob/master/User%20Stories/Description%20User%20Story%2016.pdf

**Comment by Rainer-Lampatzer** [comment]
@MariellePetitDoche 

:question::question::question:

Hi Marielle,

according to my information, you implemented the mode transitions.

In order to review the completeness of the interfaces with special regard to User Story 15 and 16, I need some clarification from you, as I am new to the project.

:question:
Circa in the middle, Storyboard 16 writes an arrow from TIU to OBU. This arrow is labeled with *Train is in standstill*
This information is essential for the mode change from TR to PT. 
But there is no signal from TIU to OBU for this information. So to what information do you refer?

:question:
Some lines below, there is a loop arrow from TIU to itself. This arrow is labeled with *Train is stopped when distance has reached D_NVPOTRP*
This information is either essential because, in PT mode, the train is not allowed to move more than D_NVPOTRP.
I doubt that TIU is able to stop the train after having moved D_NVPOTRP without contribution from OBU. But even in this case, there should be a way to transmit the value of D_NVPOTRP to TIU. Now there is no signal from OBU to TIU for this information. So to what information does TIU refer?

:question:
The lowest arrow from TIU to OBU is labeled with *Distance D_NVPOTRP has been reached*
But there is no signal from TIU to OBU for this information. So to what information do you refer?

Thanx a lot in advance!

Rainer

:question::question::question:

**Comment by MariellePetitDoche** [comment]
Hello Rainer,

"Train is in standstill" is an input for Mode&Level function provided by the odometry (in same time as the speed), not by TIU.

D_NVPOTRP is a national value provided by trackside in packet 3 (see SRS §7.4.2.1.1) or defined by default as presented in SRS 3 §A.3.2.

TIU is not involved in defining this data.

Besides I do not understand the loop on TIU in the User story, as the supervision that the train to not run a longer distance than D_NVPOTRP shall be manage by OBU  directly (by speed and supervision monitoring function).

Please check with @BaseliyosJacob the user stories.

**Comment by T12z** [comment]
As I  just mentioned in #822, this is not part of SDM, as it is not in supervision-mode. But it sure is closely linked to it.
An additional top-level component would have to be created for this: "Brake Command Handling and Protection against Undesirable Train Movement", which is the only one actually mentioning Post Trip mode

**Comment by jokaICS** [comment]
Dear Baseliyos (@BaseliyosJacob),

your original definition of this US is somewhat contradictory to the scenario we discussed in our meeting today: 

> The scenario starts after the train has tripped, e.g. by moving past the EoA 

So, originally the reason for the TRAIN TRIP was not an emergency message, but an overpassed EoA. Anyway, how far do we need to drive back after the TRIP? Until the train front end has passed over the balise at SMB 204?

**Comment by T12z** [comment]
Think of a very slippery track. And neither interlocking nor driver knowing about it. 
eg. had this last foggy, drizzly week on way home. The S-Bahn was really struggling to stop within stations while still trying to be on time.
Though don't think we can simulate low friction 

---- Johannes Kastner schrieb ----

**Comment by BaseliyosJacob** [comment]
Dear Johannes, 

please check the update of US 15 and 16. I have pushe the new version and they will now both the same, but US 16 will be with a back movement. In the Utrecht - Amsterdam Operation rules they require that the train has to drive back as far as possible - that means the train should drive back until it is at the end of ND_NVPOTRP.

**Comment by Rainer-Lampatzer** [comment]
RBC works that were obviously still open are done now together with #862

**Comment by Rainer-Lampatzer** [comment]
No content beyond #862
Further work will be done in followup project
