### ISSUE TITLE
ADD / D3.5.3 / F2.7: SpeedSupervision_Integration

### ISSUE THREAD

**Issue by mahlmann** [openETCS/modeling#735]
Dear @T12z 

with respect to #651 I did a first review of Section 5.8 F2.7: SpeedSupervision_Integration in the ADD document (https://github.com/openETCS/modeling/tree/master/openETCS%20ArchitectureAndDesign/D3.5.3) and added some comments and TODOs in this section (I refer to the ADD document for details). 

Considering that the ADD document is overdue already, I kindly ask you to take action on this issue as soon as possible.

General remark: *Please do not change the template structure, e.g. do not remove rows from the input/ouput descriptions. If a particular row is not relvant for a specific input/output just state "n/a" there.*

**Comment by T12z** [comment]
kindly ask for removal of

** superseeded by some V2, original not linked **
  * trainsupervision.tex

** [ceased living in current model, unlinked in parent model **
  * CalcSpeeds.tex
  * ReleaseSpeed_Selection.tex
  * SDM_OutputWrapper.tex

Otherwise, see update, not final completion, but a good step towards 
current model.
Thorsten

-- 
Dipl.-Ing. Thorsten Schulz
Universität Rostock, Fakultät f. Informatik und Elektrotechnik
Institut f. Angewandte Mikroelektronik und Datentechnik
18051 Rostock, Germany
+49 381 498-7278
http://www.imd.uni-rostock.de

**Comment by T12z** [comment]
kindly ask for removal of

##### superseeded by some V2, original not linked
  * trainsupervision.tex

##### ceased living in current model, already unlinked in parent model
  * CalcSpeeds.tex
  * ReleaseSpeed_Selection.tex
  * SDM_OutputWrapper.tex

Otherwise, see update, not final completion, but a good step towards current model.

**Comment by mahlmann** [comment]
Files have been removed.

Please note however, that the section numbering should stay stable _in future_ . Thus, if you remove a subcomponent you should put "intentionaly deleted" so that the subsequent section numbering will not change. The reason for this is, that the section numbers are used for referencing, especially in case of WP4.

**Comment by T12z** [comment]
thanks, good point, I forgot about that.

**Comment by T12z** [comment]
since there are no further remarks, I will close for release D3.5.3
