### ISSUE TITLE
TM::Linking information with wrong direction indicator

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#752]
The problem may be in the database UtrechtAmsterdam or in the Conversion Routines.
The linking data received after balise 353 has the following linking packet 5:
![image](https://cloud.githubusercontent.com/assets/3288918/10021051/51f2db06-6146-11e5-8f7c-a73593ed08ae.png)

q_linkorientation for balise 356 has to be reverse.
The operator Read_P005_ForCalcTrainPos is used.
The problem can be reproduced using the evc simulation model.

In the consequence of this problem the train goes in TRIP at balise 356 with reason Linking Inconsistency: Wong direction.

**Comment by mairamou** [comment]
This has been corrected.
It was an error in the packet constant definition-

**Comment by BerndHekele** [comment]
Hi,
unfortunetly the correction did not work - same behaviour.

We use this information in different locations - may we have more than one constant?

cu
Bernd

**Comment by JakobGartner** [comment]
Hmm on the track model I only see two P005 referencing BG356:

![screen shot 2015-09-22 at 22 34 38](https://cloud.githubusercontent.com/assets/8400941/10030870/4cb7affc-617a-11e5-9870-cad1907a32d0.png)

![screen shot 2015-09-22 at 22 35 00](https://cloud.githubusercontent.com/assets/8400941/10030916/7df2c1c4-617a-11e5-86fe-27a75f2f81ac.png)

I have corrected Q_LINKORIENTATION for both of them.

(1= reverse)

I will test the constants with the P005 test model...

I will also check if this is maybe a problem not related to the track model which is unlikely because the constants were not correct before this update.

**Comment by BerndHekele** [comment]
It is also an option the convertion routines are not correct. We are entering some fresh area now.

**Comment by JakobGartner** [comment]
This has been corrected (it was a wrong constant definition in TM_conversions)- so it was a double error: on track and in the conversion library.

**Comment by stefan-karg** [comment]
Dear Mairamou,

you applied the correction to the constant BG354_P005_1_L1 and BG354_P005_2_L1.

When the message 3 is created, the constants LRBG354_P005_1 and LRBG354_P005_2 are used. 
I fixed the constant there locally for testing purposes and it solved the problem.

Can you fix the constants in the model on github?

**Comment by mairamou** [comment]
Hmm,

in my model they are OK (see also the screenshots from Jakob above.
Maybe it is a sync issue on github? I will check....

**Comment by mairamou** [comment]
It seems that in the Github mess from Monday, this was lost/rolled back or something like that.
I am pushing again.

**Comment by BerndHekele** [comment]
I did a retest.
The correction is stil not visible to me.
Can you please retry with a clean repo?

**Comment by mairamou** [comment]
I had pushed on a fresh clone. 

I will check again 

2015-09-24 12:21, Bernd Hekele wrote: 

> I did a retest.
> The correction is stil not visible to me.
> Can you please retry with a clean repo? 
> 
> --
> Reply to this email directly or view it on GitHub [1].

-- 
Mairamou Haman Adji
Junior Software Developer
Research Fellow
---------------------------
LEA RAILERGY
 

Links:
------
[1]
https://github.com/openETCS/modeling/issues/752#issuecomment-142883224

**Comment by UweSteinkeFromSiemens** [comment]
@mairamou : Probably this could be one more indication of trouble on github currently. Last week, some files I pushed to github did not seem to arrive there, but in fact have been stored. This could have been caused by an automatic, but unintended renaming of files: upper-case letters were replaced by lower-case or vice-versa (I don't remember exactly). With TortoiseGit, pushing and pulling succeeded, but pulling seemed to fail with smartgit.  Please take this as hints to analyze the problem.

**Comment by mairamou** [comment]
I am using the original Github (from github.com) client for OS X since
the start of the project 

On 2015-09-24 13:10, Uwe Steinke wrote: 

> @mairamou [1] : Probably this could be one more indication of trouble on github currently. Last week, some files I pushed to github did not seem to arrive there, but in fact have been stored. This could have been caused by an automatic, but unintended renaming of files: upper-case letters were replaced by lower-case or vice-versa (I don't remember exactly). With TortoiseGit, pushing and pulling succeeded, but pulling seemed to fail with smartgit. Please take this as hints to analyze the problem. 
> 
> --
> Reply to this email directly or view it on GitHub [2].

-- 
Mairamou Haman Adji
Junior Software Developer
Research Fellow
---------------------------
LEA RAILERGY
 

Links:
------
[1] https://github.com/mairamou
[2]
https://github.com/openETCS/modeling/issues/752#issuecomment-142899438

**Comment by JakobGartner** [comment]
@BerndHekele

I have checked my local (fresh) pull of the repository.

The changes are there. 

Which version of the track model (there are several in the model) are you using ?

**Comment by JakobGartner** [comment]
(I am not checking what shithub is saying, I am checking in the pulled model files)

**Comment by mairamou** [comment]
We found the error for this particular problem 

It was my mistake. 

I push again 

(the problem has nothing to do with the current Github issue) 

On 2015-09-24 12:21, Bernd Hekele wrote: 

> I did a retest.
> The correction is stil not visible to me.
> Can you please retry with a clean repo? 
> 
> --
> Reply to this email directly or view it on GitHub [1].

-- 
Mairamou Haman Adji
Junior Software Developer
Research Fellow
---------------------------
LEA RAILERGY
 

Links:
------
[1]
https://github.com/openETCS/modeling/issues/752#issuecomment-142883224

**Comment by BerndHekele** [comment]
solved
