### ISSUE TITLE
Passed Balise is reset in BGs_loc to not passed, when linking information for this balise are received after the balise

### ISSUE THREAD

**Issue by janWelte** [openETCS/modeling#763]
I've recognized that a BG which is passed and therefore marked with infoFRomPassing in BGs_loc is 
again placed in the BGs_loc array as not passed if repeated linking information containing this BG (in relation to an earlier BG) are received after the BG is passed.
This leads to the case that this balise could be marked as missed, also it has been found at the correct place and in accordance with all received linking information.

The presented scenario can be reproduced for BG 363 and BG 365 at the AM-UT Track as linking information in relation to LRBG 362 and LRBG 364 are received via radio at the moment the BGs are passes. BG 363 has already been announce by linking information in relation to LRBG 354 and BG365 is already know by linking information with respect to LRBG 362.

In those concrete scenarios the EVC first finds the BGs and makes them LRBG and then get the radio message from the queue containing the linking information. 

The proper behavior would be, that the system recognizes that these balises are in rear position and have been passed. Therefore, the linking information have to update (in this case they are identical) and the balises should not be reset in any way.

I guess that some part of this behavior are related to #649

**Comment by UweSteinkeFromSiemens** [comment]
In the current implementation the announcement of a BG overrides a BG with the same ID, even if it has already been passed. The reason is, that - since announcing an already passed BG is completely useless - the re-announcment is taken as "will be passed" again, for whatever reason. 

To improve the resistibily against announcements of already passed BGs, I will change the behavior:  re-announcements will no longer have an override impact on the stored information.

**Comment by UweSteinkeFromSiemens** [comment]
@janWelte : Accomplished? May I close this issue?

**Comment by UweSteinkeFromSiemens** [comment]
yes.
