### ISSUE TITLE
UtrechtAmsterdam: NID_LRBG correction

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#800]
In the current use of the Interfaces the LRBG is not calcualted according to the standard.
In order to correct this issue, the following models are involved:
 - UtrechtAmsterdam @mairamou 
 - TrackMessages @JakobGartner 
 - Manage_trackside Information @BerndHekele
 - CalculateTrainPosition @UweSteinkeFromSiemens 
 - RBC (?) @jokaICS  

This list might be incomplete - if you are also impacted, please use this issue for information.

Please, use this issue for corrections.

**Comment by UweSteinkeFromSiemens** [comment]
- [x] CalculateTrainPosition: done

**Comment by JakobGartner** [comment]
We have two possibilities here:

- We represent NID_LRBG in all the packets where it occurs as a 9-digit int   (and provide a library function to split it locally)
- We represent NID_LRBG as two fields NID_LRBG_c and NID_LRBG_bg in all the packets

What do you prefer?

(I guess the first option is faster to implement as nobody has to change a model  part from adding the “split function”.)

**Comment by UweSteinkeFromSiemens** [comment]
The conversion functions from NID_C / NIC_BG into NID_LRBG and back are already available in CalculateTrainPosition_Pkg::BG_utilities_Pkg.

**Comment by UweSteinkeFromSiemens** [comment]
Replacing the duality of NID_C / NID_BG || NID_LRBG by an unique representation is a good idea. But since the duality is currently propagated through a lot of functions, I'm not sure if we should spend the effort at this very late project phase.

**Comment by JakobGartner** [comment]
yes but these functions go down to bit level if i see it right, which is not the same as our integer encoding?

**Comment by UweSteinkeFromSiemens** [comment]
Please look inside CalculateTrainPosition_Pkg::BG_utilities_Pkg::nidC_nidBG_2_NIDLRBG and CalculateTrainPosition_Pkg::BG_utilities_Pkg::NIDLRBG_2_nidC_nidBG. 

They base upon a 10 + 14 bit concatenation as specified for NID_LRBG by the ETCS language.

**Comment by JakobGartner** [comment]
yes, that’s what I say.

But on the track model (and in our transport) we have a simple mapping to an integer with an offset of 5 digits to separate the two fields.

**Comment by UweSteinkeFromSiemens** [comment]
Ooops, then we have in addition a third creative representation of NID_C / NID_BG || NID_LRBG.  
All that is ok as long as we're not confused by this trinity and the conversion functions are provided. 

To be sure: 5 digits represent 5 * 4 = 20 bits? .

**Comment by BerndHekele** [comment]
Do we have a common understanding of the solution and a common set of libraries for conversion?
I just recognised the set of TM does not work.

kr
Bernd

**Comment by UweSteinkeFromSiemens** [comment]
My understanding is that of  CalculateTrainPosition_Pkg::BG_utilities_Pkg::nidC_nidBG_2_NIDLRBG and CalculateTrainPosition_Pkg::BG_utilities_Pkg::NIDLRBG_2_nidC_nidBG.

**Comment by JakobGartner** [comment]
we don’t have bitfields on the test track, and the coding is hence integer- based

**Comment by UweSteinkeFromSiemens** [comment]
@JakobGartner: That's not a contradiction.

**Comment by UweSteinkeFromSiemens** [comment]
In the current testbench_integration model, announcing linked balise groups via radio fails, caused by NID_LRBG format deviating from the standard. 

Example: 
- Received via radio: ReceivedMessageFromTrack.nid_lrbg = 42600354.
- According to Subset 026-7, 42600354 is equivalent to nid_c = 2600 and nid_bg = 1954. 

Thus, the linking packets refer to an unknown referencde BG and all linking information is ignored completely.

**Comment by JakobGartner** [comment]
On order to have a human readable format in the track model ,  we have not
encoded the stuff on bit level, but based on the JRU output formats .

I think it is easier to use the eval_lrbg operator from TM than to rewrite
the track model

Jakob Gaertner

LEA Railergy
Am Mittleren Moos 48
86167 Augsburg

j.gaertner@railergy.com
+49 821 907802-0
+49 151 25387841



On 29.10.2015, at 12:55, Uwe Steinke <notifications@github.com> wrote:

In the current testbench_integration model, announcing linked balise groups
via radio fails, caused by NID_LRBG format deviating from the standard.

Example:

   - Received via radio: ReceivedMessageFromTrack.nid_lrbg = 42600354.
   - According to Subset 026-7, 42600354 is equivalent to nid_c = 2600 and
   nid_bg = 1954.

Thus, the linking packets refer to an unknown referencde BG and all linking
information is ignored completely.

—
Reply to this email directly or view it on GitHub
<https://github.com/openETCS/modeling/issues/800#issuecomment-152156750>.

**Comment by UweSteinkeFromSiemens** [comment]
I adapted calculateTrainPosition to @JakobGartner definition, even though not complient to Subset 026. Therefore, it is currently not a problem any more.

**Comment by stefan-karg** [comment]
Fixed.
