### ISSUE TITLE
Train to Track bus: TM_radio_messages foul ground

### ISSUE THREAD

**Issue by UweSteinkeFromSiemens** [openETCS/modeling#806]
The bus and the corresponding operators seem to be inappropriate under some aspects. Referring to TM_radio_messages::Send_M155 as an example, they are: 

1.  *M_155_T.nid_message*: since the operator Send_M155 is specifically generating message 155, nid_message causes overdetermination and should be omitted.  

2. *M_155_T.l_message*: since the operator Send_M155 is specifically generating message 155, l_message causes overdetermination and should be omitted. 

3. *Send_M155.t_train_global* input vs. *M_155_T.t_train*: The types are different: Obu_BasicTypes_Pkg::T_internal_Type || T_TRAIN. Two different inputs for the same dimension with different types may cause confusion.

4. *M_155_T.nid_engine* and *Send_M155.m_version* input: Since these values are invariant for the same OBU, they should be added by the bus terminator, not propagated through the chain and need not be added by the bus clients on the way.

**Comment by JakobGartner** [comment]
> On 14 Oct 2015, at 12:37, Uwe Steinke <notifications@github.com> wrote:
> 
> The bus and the corresponding operators seem to be inappropriate under some aspects. Referring to TM_radio_messages::Send_M155 as an example, they are:
> 
> M_155_T.nid_message: since the operator Send_M155 is specifically generating message 155, nid_message causes overdetermination and should be omitted.
> 

no. The nid_message is required in order to correctly decode the message on the receiving end.
In other word, once in the bus, the aid_message is needed to correctly identify a message.
> M_155_T.l_message: since the operator Send_M155 is specifically generating message 155, l_message causes overdetermination and should be omitted.
> 
no. The nid_message is required in order to correctly decode the message on the receiving end.
In other words, once in the bus, the aid_message is needed to correctly identify a message.
> Send_M155.t_train_global input vs. M_155_T.t_train: The types are different: Obu_BasicTypes_Pkg::T_internal_Type || T_TRAIN. Two different inputs for the same dimension with different types may cause confusion.
> 
> 
You are right in principle. 
But, this has a background.
At the moment t_train is being ignored on the input side. t_train_global is not used at the cycle where the message is sent by the operator in charge, but at the cycle the message is actually being merged onto the bus. This is necessary in order to have a unique T_TRAIN per message.

The t_train field is then used on the output side.

**Comment by UweSteinkeFromSiemens** [comment]
nid_message is definitely required to be transferred on the bus for message identification. It should be added by the Send_M155 operator itself. The ability to apply a nid_message different from 155 to Send_M155 is an unnecessary source of malfunction. 

The similar applies for l_message.

**Comment by JakobGartner** [comment]
Well,

yes, that would be more fool- proof.

But I won’t touch it now for priority reasons. We can touch it when we are through the critical phase.

For l_message: This is ignored anyway.


Thanks…


Jakob

**Comment by UweSteinkeFromSiemens** [comment]
That's fine.

**Comment by UweSteinkeFromSiemens** [comment]
Downgraded to potential enhancement.
