### ISSUE TITLE
Demonstrator: Visualization of Braking Curves

### ISSUE THREAD

**Issue by jokaICS** [openETCS/modeling#807]
Dear Thorsten @T12z,

I'd like to start a discussion on how we can extract the braking curves data required for our demonstrator. My idea would be to add an imported operator to the SDM component, which periodically sends the data to the simulation UI via TCP/IP. That way, we don't need to modify the SDM interface (unless the SDM already provides all necessary information at its interface).

BR, Johannes

**Comment by T12z** [comment]
The braking curves are all "well-fenced" within SDM, no interfaces.
The V&Vs probably wont like having data-trap-doors within the module, but it could be the most efficient way.

I didn't keep up with all the demonstrator architectures,
but is this fixed on TCP, or is UDP a chance as well? We (URO) are planning for some inhouse demos, but are limited by the RTOS to UDP, since TCP is non-deterministic.

What curves are planned to be shown? Currently all EBDs and SBD are generated, (no guidance curve). The derived curves (I, P, FLOI ...) are sampled each cycle, not recreated. I and W is only calculated for the Most-Restrictive-Target.

Maybe, for some quick mileage, we should grab a phone tomorrow. I am available most day.
cheerio, T.

**Comment by jokaICS** [comment]
> The V&Vs probably wont like having data-trap-doors within the module, but it could be the most efficient way.

You're right, for verification that usually would be not acceptable; but I think an additional interface which is purely used for the demonstration is also not desirable (esp. since it also would introduce an additional interface on the EVC level).

> but is this fixed on TCP, or is UDP a chance as well?

Since it's only meant for async one-way communication, UDP is OK. However, it's probably best to provide a separate implementation of the imported operator for your own demo, since our lib would possibly need stripping down before it can be compiled for the RTOS.

> What curves are planned to be shown?

I'm no expert on this topic; I'd say everything that's easily accessible?

> Maybe, for some quick mileage, we should grab a phone tomorrow.

Yes, I'll give you a call.

**Comment by T12z** [comment]
status / time slot?

**Comment by T12z** [comment]
there is quite something to show:
first up, `SpeedSupervision_Integration_Pkg::SpeedSupervision_Integration/`:
![sdm-101](https://cloud.githubusercontent.com/assets/10432699/10579574/29ba9a6e-7679-11e5-8962-26ed2fb53fdf.PNG)
== The EBD curves==
The blue circle in the middle contains the SBD-curve (Service-Brake), the Speed-restriction(MRSP)-EBD-curves (array of curves) and the SvL/LoA-EBD-curve. The latter are two distinctive curves, but they are exclusive. So you either have an EoA and a related SvL, or you have an LoA, no SBD but an LoA-EBD-curve. All EBD, but the SvL-EBD, have an end-speed v_target <> 0!
For display purposes it is quite adequate to assume that the length of the MRSP-curve-array is less than 10 (instead of the defined 200!)

Each curve is constructed out of of arcs, described each by deceleration (absolute value), distance (that is location on the track) and speed of the root point of the arc. It is important to understand, that the curve is constructed from the target-point backwards to the train. Don't rely on this wording, because the starting point tends to be slight behind the target location:
![srs-26-3 13 8 3 figure 40](https://cloud.githubusercontent.com/assets/10432699/10580107/3bcf77bc-767c-11e5-93dd-09df87854787.PNG)
Anyways, the curve is still constructed from the EBD-foot upwards.
![srs-26-3 13 6 figure 38](https://cloud.githubusercontent.com/assets/10432699/10580188/9e4fd1c0-767c-11e5-82a9-fe274096a515.PNG)
For some historical reasons, the curve is actually a column array, aka. an array of vectors distances, speeds, accelerations. Btw. all values so far are real, metric base units, m, m/s, m/s²

== Targets of the curves ==
... are in the target collection (left blue circle) and the MostRestrictiveTarget (right blue). Targets mark the location (name "distance"), its speed and its type. Each target has a related curve.

== More overlays == 
There is the MRSP-array, consting of the MostRestrictiveSpeedProfile along the track. Then, in red on the right, special markers for intervention with the structs *speeds* and *locations*. Pretty much the ones seen in Figure 55 and 56.

**Comment by jokaICS** [comment]
Thanks for your elaborate explanation. I think it would be helpful to discuss with Baseliyos  (@BaseliyosJacob) which braking curves he actually wants to see.

**Comment by jokaICS** [comment]
@T12z sorry for the delay... I've now implemented a `ProbeSDM` operator to extract the braking curves data. Currently, it provides inputs for the three flows encircled in blue in your previous post. To use it you need to add `test/EnvSim/Scade/EnvSim.etp` to your project. Then you should find ProbeSDM in package EnvSim.

**Comment by T12z** [comment]
sure, no rush.
But please, do not include `SpeedSupervision_Integration.etp` I run into a recursion. Instead include the special subproject `SDM_Types.etp`. Actually I have included this change in the commit. If this interferes with anything of your changes, I could just revert. practically it is a one-liner.

Anyways, I included the probe operator but I cannot compile the testbench due to an empty struct. I tried to circumvent this with a *char dummy*, but with the next interruption (unknown type name 'SV_ProbeSDM_EnvSim') I gave up. I cannot commit an uncompilable package, sorry. Please hint what needs fixing.

**Comment by jokaICS** [comment]
> But please, do not include SpeedSupervision_Integration.etp I run into a recursion. Instead include the special subproject SDM_Types.etp. Actually I have included this change in the commit. If this interferes with anything of your changes, I could just revert. practically it is a one-liner.

No, that's fine, thanks.

> Anyways, I included the probe operator but I cannot compile the testbench due to an empty struct.

I cannot check right now, since a model error currently prevents code generation. Anyway, could you post the actual error message (what do you mean by "empty struct")?

**Comment by T12z** [comment]
in a possibly generated h-file a typedef struct {}; does not contain any definitions, which makes the compiler complain:
https://github.com/openETCS/modeling/blob/master/test/EnvSim/libenvsim/src/scade/ProbeSDM_EnvSim.h
I am currently pushing the model to my personal fork at github, but this may still take an hour. (don't ask)

**Comment by jokaICS** [comment]
gcc should usually accept empty structs and only emit a warning. Do you use the option "Set warnings as errors"? Can you compile the operator EnvSim::Internal::GenAll in the EnvSim project (you need to select the "SimulationJK" profile)?

**Comment by jokaICS** [comment]
I've added a dummy output to the ProbeSDM node; this should solve the issue.

**Comment by jokaICS** [comment]
I've integrated the ProbeSDM operator into your prepared diagram SpeedSupervision_Integration_ProbeSink and pushed the modified .xscade file.

**Comment by jokaICS** [comment]
@T12z regarding the CalcBrakingCurves_types::ParabolaCurve_T type: how can I check how many of the curve segments are really used/valid?

**Comment by T12z** [comment]
Sorry, missed the notification about your question:
There is no length field. All valid curve arcs should be marked valid == true. There should be only two parts in a curve-array, the first only consisting of valid arcs, the rest only empty arcs. So the first invalid arc marks the end.

**Comment by jokaICS** [comment]
Hmm, I see a valid flag for each ParabolaCurve_T; but every curve has up to 114 entries for distance, speed and acceleration. How do I know which of those are valid?

**Comment by T12z** [comment]
Once again, something's broken with my notification on this,

doesn't it also have equal length valid array (next to dist., speed and acc.)? (Sorry not on the design machine at the moment)

**Comment by jokaICS** [comment]
> doesn't it also have equal length valid array (next to dist., speed and acc.)? (Sorry not on the design machine at the moment)

Sorry, you're right :$ I didn't realize that .valid was an array -- thanks.

**Comment by T12z** [comment]
oooooook, I see what you're on. They are either all true, or all false.
Well in that case, with all my "German politeness": Mal verliert man, mal gewinnen die Anderen :wink:
This comes from the current implementation with the lambda-brake-model which was glued onto the earlier curve-algorithm. The whole apparatus would need a larger optimization-refactoring to sheer off the fat. And it will not happen this year, sorry. If there will ever be a gamma-brake-implementation, then this refactoring would make sense, before it may just be double work.

**Comment by T12z** [comment]
@jokaICS if you haven't already noticed, with recent tests I have also seen non-continous braking curves -- though in this case it was only an SBD curve. So the assumption that once the values do not change, that's the end of the curve, was *wrong*. This essentially means, until further refactoring, you always have to parse the whole array. SORRY for that!

**Comment by jokaICS** [comment]
@T12z thanks for the info (wasn't aware of that).
Another question: if I'm not mistaken, the target speed in the EOASBD curve collection is never 0? For instance, while we're driving in NTC with the "fake" MA, the traget distance is 48692m, the deceleration 0.78 m/s^2, and the target speed 50m/s? Is this correct, or am I misinterpreting the data?

**Comment by jokaICS** [comment]
@T12z OK, my last question is solved; when I iterate over all possible elements of a braking curve, I find the last segment with target speed 0 -- thanks for now :)

**Comment by jokaICS** [comment]
@BaseliyosJacob, @T12z  
I've pushed a first implementation of the braking curves visualization; there's still a lot to do (static speed still missing, and I don't see valid MRSP curves after the level transition -- is this correct?).
![image](https://cloud.githubusercontent.com/assets/13429700/11768580/cf7bd66a-a1d1-11e5-8672-db187c4c65bc.png)

**Comment by T12z** [comment]
The latter is correct. There is no speed target before the end of the line. One of 140km/h appears at around 27km to make the step down into ATB. It should even intersect the EoA intermittently. 

I won't have much of a chance to look into it before Munich though. But don't hesitate to ask if something's bugging you. 

---- Johannes Kastner schrieb ----

**Comment by jokaICS** [comment]
Basic visualization of braking curves in SimCtrl has been implemented. Improvements (continuous plot in particular) should be considered if there should be a future maintenance release of libenvsim/SimCtrl.
