### ISSUE TITLE
SysML / F2.7 SpeedSupervision_Integration overview

### ISSUE THREAD

**Issue by mahlmann** [openETCS/modeling#814]
@T12z 

the SysML representation of OBU block F2 consists out of 13 diagrams, one for each functional component. The diagram for _F2.7 SpeedSupervision_Integration_ has been created (c.f. attached screenshot). Please check if the diagram is 
- [ ] complete (e.g. some links may be missing)
- [x] correct (e.g. consistent with the SCADE Suite model)

The diagram is located here: https://github.com/openETCS/modeling/tree/master/model/sysml/openETCS_EVC . 

In case of findings please use the issue tracker or -- if you want to implement corrections by yourself -- please inform me beforehand to avoid merge conflicts.
![capture](https://cloud.githubusercontent.com/assets/3638145/10513097/805e8d76-7345-11e5-924f-51b42b76ae8e.PNG)
Relates to #489

**Comment by T12z** [comment]
Input from TrackAtlas is missing - this may be due to other issues, so *I* am taking *no* action. (and, my current temporary license has no System features)
Specifically `dataFromTrackAtlas` and `NationalValues` are missing, both of them coming from track side.
There might be an error in `IBD_ETCS Kernel F2.3`: trainData::actualTrainData is linked to SpeedSupervision_Integration::trainProps. It should be linked to trainData.
trainProps seems to have some kind of scattered architecture, being a composite of different outputs.

**Comment by T12z** [comment]
And :+1: @mahlmann, good job on the overall architecture! This really helps when looking beyond the own package.

**Comment by mahlmann** [comment]
Thanks for your feedback
- dataFromTrackAtlas has been fixed (TrackAtlas needed to be integrated first, therefore this input was pending)
- NationalValues has been connected to API_persistentData input of F2
- trainData::actualTrainData is acutally connected to trainData and trainProps via some intermediate logics/components. This is also the reason for the "scattered architecture" you mention. I am well aware of this. In SCADE Suite there is some additional logic between these inputs/outputs which is not visible in SysML. I think this should be fixed on SCADE Suite site in the integration model.
