### ISSUE TITLE
DMI <-> EVC Messages, and the "present" flag

### ISSUE THREAD

**Issue by Farhangi** [openETCS/modeling#824]
The "present" flag is in the DMI <-> EVC Messages  true even if  it is to be sent no package.
Is it a bug?  or the flag represents the communication between components?

**Comment by BerndHekele** [comment]
The message should only show-up when updated packets are available.
I will test the behaviour and take this as an error.

**Comment by jokaICS** [comment]
How do we know when there is actually data to be sent? AFAIS the first int in the messages ("present") is always 1?

For the IP-based comm we really should only send messages when there is actually an update (if we send messages in every cycle, we really run into some issues, since sender and receiver will never run with exactly the same frequency and then we need to either discard messages or implement some elaborate flow control...)

**Comment by Farhangi** [comment]
In "Testbench_Integration" , 

the operator "Messages::CAST_DMI_to_EVC_to_int" should be replaced with "Messages::Write_DMI_to_EVC_to_int".

the operator "Messages::CAST_int_to_EVC_to_DMI" should be replaced with "Messages::Write_int_to_EVC_to_DMI".

**Comment by jokaICS** [comment]
@Farhangi Thanks, but the current implementation of Messages::Write_DMI_to_EVC_to_Int does not solve my problem: the DMI still sends a message in every cycle, since the present flag seems to be always true, even if there is no valid data.
Hence I propose to use the valid flags of the distinct sub structs to trigger the boolean activate, instead of the present flag, i.e. a message should only be sent if at least one of the valid flags is true (the same algorithm should be used for EVC_to_DMI).

**Comment by BerndHekele** [comment]
Hi Johannes,
if it is present all the time it is most likely a bug in my part of the DMI-Interface.
I will doublecheck when I continue testing.

**Comment by jokaICS** [comment]
OK; would it be possible to have a temporary workaround in the Write_DMI_to_EVC_to_int operator (I could do it, if Peyman has no time)? This is somewhat a blocking issue for my tasks...

**Comment by BerndHekele** [comment]
I have the model running now.
I see the interface EVC - > DMI look fine now.
In the interface DMI -> EVC the solution is hard coded:
![image](https://cloud.githubusercontent.com/assets/3288918/10630739/5541a338-77d9-11e5-9193-9e78c1f8a8d8.png)

This part needs correction (in the toolbox).
I'm still a bit disaponted about the missing boundary of the DMI_Controller. So, maybe Johannes can take the quick-fix in the toolbox and Peyman has a look at the final solution in the DMI Controller?

@stefan-karg : is there any reason for having this sort of interface in the toolbox?

**Comment by JakobGartner** [comment]
I think that in the final solution Toolbox shall have no functionality at all as far as EVC <——> DMI and EVC <——> RBC/Track comms are concerned.

**Comment by jokaICS** [comment]
OK, I will correct the DMI->EVC part in the toolbox.

**Comment by Farhangi** [comment]
It should be fixed now

**Comment by jokaICS** [comment]
@Farhangi Thanks, seems to work fine now.
