### ISSUE TITLE
Need help using github under tortoise

### ISSUE THREAD

**Issue by Rainer-Lampatzer** [openETCS/modeling#825]
Dear all,

first of all, please forgive me to be a total github newbie. In 23 years of work, I was always inwoöved in projects that used other ways to checkout  and checkin files.

Following the strong recommendation of my collegue @jokaICS, I installed tortoise SVN as a frontend to github. Johannes himself is not a tortoise user, so he can not help me using tortoise.

The tortoise help does not offer any information how to connect tortoise to Github. So can anyone please help me?

Thanks in advance,

Best regards,

Rainer

**Comment by stefan-karg** [comment]
Dear Rainer,

there are two versions existing for the Tortoise client: TortoiseSVN and TortoiseGit.
In order to interact with github, I recommend you to use TortoiseGit, even though github offers the possibility to checkout a repository using a Subversion interface.

You can download the client here: https://tortoisegit.org/

The first step is to perform a clone of a repository, which copies the current state of the repository on github to your computer (not only a working copy but complete history of the repository). The URL to use for the clone is always mentioned beside the main page of the respective repository.

For the modeling repository, the URL is: https://github.com/openETCS/modeling.git

Best regards
Stefan

**Comment by Rainer-Lampatzer** [comment]
Hi Stefan,

thank you, I will try.

Rainer

**Comment by Rainer-Lampatzer** [comment]
Hallo Stefan,

TortoiseGit ist jetzt installiert. Jegliche Aktion wird jetzt mit "Git for Windows not found" beantwortet.

Was ist zu tun?

Gruß, Rainer

Rainer

**Comment by stefan-karg** [comment]
Hallo Rainer,

du musst git für Windows noch installieren. Eine .exe, die alles notwendige installiert findest du hier:
https://git-scm.com/download/win

TortoiseGit sollte die git-Installation automatisch finden.

Viele Grüße
Stefan

**Comment by Rainer-Lampatzer** [comment]
Hallo Stefan,

danke erst mal.

Soweit alles erledigt.

Wir sollten danach per Mail weitermachen, ist s.karg@railergy.com korrekt?

Gruß, Rainer

**Comment by stefan-karg** [comment]
Hallo Rainer,

genau, die E-Mail ist korrekt.

Viele Grüße
Stefan
