### ISSUE TITLE
TrackAtlas:Package MA_Request is missing

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#829]
I get several type 7 errors from the trackAtlas.

![image](https://cloud.githubusercontent.com/assets/3288918/10560904/277037d4-7519-11e5-89a3-a43475aa6e49.png)

**Comment by JakobGartner** [comment]
The content of MA request is not intended to be extracted from the TrackAtlas as it is closely coupled with the same.

I was  therefore not aware that it used outside of TrackAtlas context.

The package has been renamed in order to have consistent naming. 

I will make a copy with the old name as a workaround but we need to discuss the architecture as we probably don’t want to have  parallel instances of a function running.

**Comment by BerndHekele** [comment]
This package has not been used ouside your model. The error comes from your model.

**Comment by BerndHekele** [comment]
To be precise: the current deliverable produces compile errors in the models of interface partners MA-request - evc resp.DMI. 
This interface change is yet another surprise.

**Comment by BerndHekele** [comment]
I'm blocked with this change. Can you pleas provide a working interface to DMI with documented interfaces.
Alternative is to fall back on Github.

**Comment by JakobGartner** [comment]
The name of the package has already been changed back.

**Comment by JakobGartner** [comment]
I have analysed the problem:

While the “official” exported types from TrackAtlas are in TrackAtlasTypes, this was different to historical reasons (different designer) for MA_Request package- so some types and constants I considered internal were used outside TrackAtlas, which lead to unexpected broken references when the internal path was changed.

In order to not loose time. I propose not to clean the types now.

Instead, I have left the type definitions for TA_MA_request in the package TA_Request so that you can use the latter outside of TrackAtlas while TrackAtlas internal structure can be cleaned without visible changes outside-

**Comment by BerndHekele** [comment]
Solved
