### ISSUE TITLE
RBC_Messaging_Pkg::RBC_RadioTrainTrack_Pkg::RadioTrainTrackHeader__IsPresent/ blocks message 155

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#831]
The check results in false.
I assume and test the following change:
![image](https://github-cloud.s3.amazonaws.com/assets/3288918/10566128/ae82e2e2-75de-11e5-93eb-2b327fec0903.png)

**Comment by BerndHekele** [comment]
Assumption was not correct.
Constants for "undefined"and "max" are wrong defined.
![image](https://github-cloud.s3.amazonaws.com/assets/3288918/10566188/21cb8ca8-75e0-11e5-9a16-356b3628c54b.png)

**Comment by jokaICS** [comment]
I've corrected the erroneous constants introduced by the type change of T_TRAIN. However, I'm still unsure about the meaning and correct value for `T_TRAIN_UNDEFINED`.

**Comment by BerndHekele** [comment]
Thanks for the quick reaction.
If not defined in the SRS (section 7) I propose to use -1 for the undefined value.

**Comment by jokaICS** [comment]
Well, that's the problem: according to the SRS, the undefined value actually is uint32.max. But our T_TRAIN int is signed, so this value is mapped to -1 (which is not problem, since we don't use it in comparisons). T_TRAIN_MAX however should be uint32.max - 1, which maps to -2; that's why the comparison in the RBC message consistency check failed (this was not an issue while T_TRAIN was a float). Hence I've defined T_TRAIN_MAX to be int32.max (2.147.483.647), so that the RBC actually does not conform to the SRS. How does the EVC handle this issue?

**Comment by BerndHekele** [comment]
I have just set undefined to be -1. The range of t_train is between 0 and max as seen above. Se - should be consistent with your solution.

**Comment by BerndHekele** [comment]
solved
