### ISSUE TITLE
US-15/16: POST TRIP and handling of Msg 6

### ISSUE THREAD

**Issue by jokaICS** [openETCS/modeling#836]
It seems that not all requirements of the TRIP/POST TRIP procedure are currently implemented by the EVC; who is responsible for the handling of Msg 6 (@jokaICS)?

**Comment by BaseliyosJacob** [comment]
@MariellePetitDoche can you give us your analysis to this issue? Please

**Comment by MariellePetitDoche** [comment]
Modes Scade model has been verified by Marc Behrens and he has analyzed requirements and I have answered, see #803 for an extensive and explicit analysis.

If you think that some requirements have been missed, thanks to be very explicit and give exactly the reference of the requirements. Otherwise it will be difficult to make an analysis.

According the information given in this issue for the moment the only think I can say is that the input Msg6 used by M&L Management was not implemented by Track Atlas, as all the messages inputs, the last time I had a look on it.
It seems a good starting point for an analysis of this issue.

**Comment by Rainer-Lampatzer** [comment]
RBC works that were obviously still open are done now together with #862

**Comment by Rainer-Lampatzer** [comment]
No content beyond #862
