### ISSUE TITLE
TM_conversions: CAST warning in build

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#843]
I am concerned about this waning during building:

![image](https://cloud.githubusercontent.com/assets/3288918/10630257/d8279608-77d5-11e5-8fdf-eb01354e685d.png)

Can we get rid of it?

**Comment by JakobGartner** [comment]
Hello Bernd,

the problem here is that the boundary checks (that are prepared and not yet used) contain constants that exceed 32 bit value. 

As they are not used for now, I will use a lower value to have it look clean. 
(The problem is deeper: T_TRAIN and also NID_RADIO as defined in the SRS do not fit into 32bits—, but as our train will not live so long it should not be a real problem…


Fixed in the next push.

**Comment by jokaICS** [comment]
Sorry for hijacking this thread, but it's an issue that needs to be clarified (and the V&V guys should know about it):
I think T_TRAIN does fit in a 32bit *unsigned* int, but we're using a signed int for it. So actually, our T_TRAIN does not conform to the SRS (which is also the reason, that the constants T_TRAIN_MAX and T_TRAIN_UNKNOWN used in the RBC are not concordant to the values defined in the SRS; see #831). However, this should not be an issue, as long we don't compare T_TRAIN values outside the 31bit-range with < or >.

**Comment by JakobGartner** [comment]
yes, I thought in this direction too.
unsigned 32 (we can tell KCG to map the int to that size) would be a solution, however we have many instances of negative values being used (for example to mark invalid data in some cases)

As long as we don't clean all this, the safe solution is to stay with the current implementation and make sure that our values don't exceed the size we can accommodate.

**Comment by JakobGartner** [comment]
I will use the defined in T_TRAIN_MAX and T_TRAIN_UNKNOWN  for the boundary checks.

**Comment by BerndHekele** [comment]
solved.
