### ISSUE TITLE
Speed-Profile for Utrecht-Amsterdam

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#852]
To continue testing and also in order to have some basic presentations for the review I need an overview about the track, preferred in xls, covering the following information:

1. Position on the track
2. Speed Limit (maybe more) on this position (speed profile) for the whole track
3. BG-ID of passed bgs
4. Gradient
5. Special Markers like signals, switches, TSR, text messages etc.

Do we already have this information in some place?

@JakobGartner @mairamou

**Comment by jokaICS** [comment]
Maybe the simple TrackViewer we've implemented for scripted track operator would be useful to you?

**Comment by BerndHekele** [comment]
Can you specify this idea a little bit more? Where can I find it to have a look at?

**Comment by mairamou** [comment]
I will take the info that I have and merge it in one .xls . Not much
work ... 

On 2015-10-23 17:44, Bernd Hekele wrote: 

> To continue testing and also in order to have some basic presentations for the review I need an overview about the track, preferred in xls, covering the following information: 
> 
> * Position on the track
> * Speed Limit (maybe more) on this position (speed profile) for the whole track
> * BG-ID of passed bgs
> * Gradient
> * Special Markers like signals, switches, TSR, text messages etc.
> 
> Do we already have this information in some place? 
> 
> @JakobGartner [1] @mairamou [2] 
> 
> --
> Reply to this email directly or view it on GitHub [3].

 

Links:
------
[1] https://github.com/JakobGartner
[2] https://github.com/mairamou
[3] https://github.com/openETCS/modeling/issues/852

**Comment by jokaICS** [comment]
You can find the tool in modeling/test/EnvSim/tools/ -- just run trackedit.bat, and a simple UI should show up. Via File->Open you then can load a track file; our AmsterdamUtrecht track as implemented by Mairamou in Scade is located at modeling/test/EnvSim/track/AmsterdamUtrecht.trk (I think the current track file is a little outdated since Mairamou added some balises at the end of the track, but the beginning of the track should be correct -- I will upload a new version soon).

In the left column you will see all balise telegrams and radio messages defined on the track (position in meters). When you selected a BG or MSG in the left column you can view its header vars and contained packets on the right:

![image](https://cloud.githubusercontent.com/assets/13429700/10700593/249ae108-79bf-11e5-9f30-5a0a93f738eb.png)

**Comment by jokaICS** [comment]
I've pushed the updated track file.

**Comment by BerndHekele** [comment]
Thanks Johannes for this great tool. I will use it in future.
It is an excellent starting Point.

However, I had something slighly different in mind.
I would like to see the Speed Limits as they are linked to the track caused by packet 27.
Is this something we can generate out of the data we have available?

And to work / visualise such data I would like to have them in xls. 
We could use this graph as a graf in slides.

**Comment by jokaICS** [comment]
Ahh, sorry for the misunderstanding. It would be possible to write the gradient data to a CSV, but it's probably more efficient to wait for Mairamou's merged Excel sheet.

**Comment by mairamou** [comment]
Here you have a first version.
I did not put so much effort now, I will refine the data and add other events but some of them will take more time as I have to extract them from the track plans. 

[XREF_Profiles_Amsterdam_Utrecht.xlsx](https://github.com/openETCS/modeling/files/19806/XREF_Profiles_Amsterdam_Utrecht.xlsx)

**Comment by mairamou** [comment]
Very simple first graphs 
![xref_profiles_amsterdam_utrecht](https://cloud.githubusercontent.com/assets/11831051/10705764/9ed45bea-79e0-11e5-890e-c41b87f7e543.jpg)

**Comment by BerndHekele** [comment]
Thanks - that's perfect for the start

**Comment by mairamou** [comment]
Here is an update of the file. 

Change record: 

corrected data for 2nd MA message received (after passing BG351) 

Added locations where MA messages are received in tabs Events and MAs 

On 2015-10-23 17:44, Bernd Hekele wrote: 

> To continue testing and also in order to have some basic presentations for the review I need an overview about the track, preferred in xls, covering the following information: 
> 
> * Position on the track
> * Speed Limit (maybe more) on this position (speed profile) for the whole track
> * BG-ID of passed bgs
> * Gradient
> * Special Markers like signals, switches, TSR, text messages etc.
> 
> Do we already have this information in some place? 
> 
> @JakobGartner [1] @mairamou [2] 
> 
> --
> Reply to this email directly or view it on GitHub [3].

 

Links:
------
[1] https://github.com/JakobGartner
[2] https://github.com/mairamou
[3] https://github.com/openETCS/modeling/issues/852

**Comment by BerndHekele** [comment]
The picture is showing the MA-s.
If we overlay the position of the level change I interpret this information in a way the 40 km / h area is in level ntc.

Level change happens about balise 351 at m 3600.

**Comment by mairamou** [comment]
According to my model and data the level change is at m3602, so yes. 

(you can see this in the Tab "Events" in my excel ) 

the initial speed is 40km/h in level 2, as I interpret the text as
translated by Shivana and the ATB analysis by Jakob, the speed in NTC at
transition (and since leaving Amsterdam Amstel stop) should also be
40km/h 

What I find more interesting is the situation at Utrecht, where in L2
the train receives MA and MRSP beyond the transition point back to NTC,
which I interpret as an overlay to the ATB speeds that will be found
after the transition (as the speed steps are standard ATB speed
increments) 

On 2015-10-26 10:12, Bernd Hekele wrote: 

> The picture is showing the MA-s.
> If we overlay the position of the level change I interpret this information in a way the 40 km / h area is in level ntc. 
> 
> Level change happens about balise 351 at m 3600. 
> 
> --
> Reply to this email directly or view it on GitHub [1].

 

Links:
------
[1]
https://github.com/openETCS/modeling/issues/852#issuecomment-151068890

**Comment by BerndHekele** [comment]
Your interpretation is correct and according to the standard.
We always need to have this overlap.

**Comment by BerndHekele** [comment]
By the way - where can I find the mentioned xls?
I did not see a reasonable link in the resent information.

**Comment by mairamou** [comment]
[XREF_Profiles_Amsterdam_Utrecht.xlsx](https://github.com/openETCS/modeling/files/20780/XREF_Profiles_Amsterdam_Utrecht.xlsx)

Here is a file that I use to check consistency etc. 
It will grow with additional topics (for example EM)

**Comment by mairamou** [comment]
Should I adapt the NTC speed profile then? 

Even if it is not used most of the time, it would be nicer and not much
work. 

On 2015-10-26 11:37, Bernd Hekele wrote: 

> Your interpretation is correct and according to the standard.
> We always need to have this overlap. 
> 
> --
> Reply to this email directly or view it on GitHub [1].

 

Links:
------
[1]
https://github.com/openETCS/modeling/issues/852#issuecomment-151095645

**Comment by BerndHekele** [comment]
This also rfers to #860 

Yes - we need to fix both ends of this ntc story.

**Comment by BerndHekele** [comment]
Done.
Thanks
