### ISSUE TITLE
UtrechtAmsterdam: Message LRBG371 - 3 is not sent.

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#861]
Communication of Messages after balise 371 is not visible in the evc.
Radio Communication is active at this p.o.t.
I assume we have a problem in the track definition.
Do I need to collect frther symptoms?

@mairamou 
@JakobGartner 

Result is train is running without ma.
see also #856

**Comment by JakobGartner** [comment]
The TrackModel is complete, as also already validated by Johannes and Jan.

However the RBC messages on the track need a trigger…. if not they don’t do anything.

**Comment by janWelte** [comment]
Jakob is right. It has to be checked whether the trigger is send. We have not been able to verifiy the trigger interaction as these models have not been defined completely before.

**Comment by jokaICS** [comment]
Jakob is right, the trigger ops are missing — I’m on it, sorry…

Am 26.10.2015 um 12:41 schrieb Jakob Gärtner <notifications@github.com<mailto:notifications@github.com>>:

The TrackModel is complete, as also already validated by Johannes and Jan.

However the RBC messages on the track need a trigger…. if not they don’t do anything.



> On 26 Oct 2015, at 12:39, Bernd Hekele <notifications@github.com<mailto:notifications@github.com>> wrote:
>
> Communication of Messages after balise 371 is not visible in the evc.
> Radio Communication is active at this p.o.t.
> I assume we have a problem in the track definition.
> Do I need to collect frther symptoms?
>
> @mairamou <https://github.com/mairamou>
> @JakobGartner <https://github.com/JakobGartner>
> Result is train is running without ma.
> see also #856 <https://github.com/openETCS/modeling/issues/856>
> —
> Reply to this email directly or view it on GitHub <https://github.com/openETCS/modeling/issues/861>.
>


—
Reply to this email directly or view it on GitHub<https://github.com/openETCS/modeling/issues/861#issuecomment-151107601>.

Mit besten Grüßen

Johannes Kastner

--
Johannes Kastner
Dipl.-Ing.
Software-/Systemingenieur
Research & Development
Phone: +49 711 21037 – 41
Fax: +49 711 21037 – 53
Mobile: +49 172 7280529

E-Mail: johannes.kastner@ics-ag.de<mailto:johannes.kastner@ics-ag.de>
Internet: www.ics-ag.de<http://www.ics-ag.de/>


Informatik Consulting Systems AG

Address: Sonnenbergstr.13, 70184 Stuttgart / Mailing Address: Postfach 102431, 70020 Stuttgart, Germany
Domicile and Court of Registry: Stuttgart / Commercial Register No.: HRB 18569
Chairman: Dr. Philipp Bauer / Management Board: Franz-Josef Winkel, Cid Kiefer

This e-mail message may contain confidential and/or privileged information. If you are not an addressee or otherwise authorized to receive this message, you should not use, copy, disclose or take any action based on this e-mail or any information contained in the message. If you have received this material in error, please advise the sender immediately by reply e-mail and delete this message.Thank you.

**Comment by jokaICS** [comment]
@BerndHekele I've pushed the triggers up to the message @302.7m after BG387. More is in work...

**Comment by jokaICS** [comment]
Triggers should be complete now.

**Comment by BerndHekele** [comment]
Solved
