### ISSUE TITLE
RBC_Messaging with compile errors

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#871]
I get a set of Compile errors from RBC-Model.
This is blocking our activities.

![image](https://cloud.githubusercontent.com/assets/3288918/10783978/be7190f2-7d5b-11e5-9ae8-c4b3b362d889.png)

**Comment by JakobGartner** [comment]
This is a duplicate of #870 .

This is fixed.

I pushed back the old version of TM_old_versions::SEND_MergeRadioPackets

I also added a function TM_old_versions::SEND_MergeRadioPackets_still_old which has an additional parameter input to send also a P42.

@Rainer-Lampatzer : Please use the new operator when sending your packet 42, and only push your model when it is consistent again.

Remark: the package TM_old_versions has been announced to be obsolete since March.

**Comment by BerndHekele** [comment]
Solved
