### ISSUE TITLE
Calculation of D_preindication 

### ISSUE THREAD

**Issue by christianstahl** [openETCS/modeling#875]
Dear @T12z ,

it seems to me that the current calculation of D_preindication in TargetLimits_Pkg::MRSPPreindicationSelector is not correct:
The first value after starting the train is >4000m. After I reach position 3596m,  D_preindication changes to 3395m. Can you please have a look? Thanks!

**Comment by christianstahl** [comment]
at position 3758, D_preindication changes to 3435

**Comment by T12z** [comment]
Hej @christianstahl ,

please have a look at my first post in #872 . To sum it up, the first part of the track is *really awkward*.
The values, that you state all look fine to the related MAs:
1. MA=5000m @40km/h --> ~4xxx --> ok
2. @3600m you are in L2 but already in TSM due to the short MA, so d_pi must have passed
3. then the MA is extended a few meters, but the MRSP is 160km/h, so we are still in TSM

what is the contrary behaviour expected by you?

**Comment by christianstahl** [comment]
Well, I would expect that the preindication is ahead of the current location.

**Comment by christianstahl** [comment]
To calculate the trigger of an MA Request, I need to calculate how many seconds the train needs for reaching the preindication location. If this value is smaller than a parameter (currently 15s), then the MA request needs to be send. That is why I think that a preindication location behind the current location does not make sense.

**Comment by T12z** [comment]
then it needs to be send instantly. SDM cannot look beyond the current target, and if we are already in TSM, then we already passed the preindication. The preindication can only be in front of the train, if we are in CSM. And this just does not happen due to the awkward track.

**Comment by christianstahl** [comment]
OK, thanks for clarifying.:)

**Comment by T12z** [comment]
no worries! :+1:
If this cleared your question, please don't forget to close the issue
