### ISSUE TITLE
Irregular behaviour of Speed Supervision @~km 4650 - 4980

### ISSUE THREAD

**Issue by BaseliyosJacob** [openETCS/modeling#885]
Dear @T12z ,

there is still a very irregular behaviour of the Speed Supervision in TSR Modus.

The Supervision of Speed CSG is jumping beetween 140 and permitted speed.

**Comment by BaseliyosJacob** [comment]
![screen shot dmi 20](https://cloud.githubusercontent.com/assets/3975810/10894121/e1738d94-81ac-11e5-8268-19863005dbf0.PNG)

**Comment by BaseliyosJacob** [comment]
![screen shot 21](https://cloud.githubusercontent.com/assets/3975810/10894158/204ecd44-81ad-11e5-867c-e643802b110c.PNG)

**Comment by T12z** [comment]
This looks new, though I don't remember having changed anything that could have such an effect. It looks like CSG and planing area oppose each other. Last Friday I could not test because there was something broken. 
This may also be caused by inputs to SDM.

Btw thanks for the screen shots, they help. If possible, Please also include the meter-counter of the simulation window for the current track location, cheers!

---- Baseliyos Jacob schrieb ----

**Comment by T12z** [comment]
This topic has not seen any attention last days.
I still suspect this was a transient issue in track data or a Track Atlas issue, so *NOT* related specifically to SDM.

**Comment by stefan-karg** [comment]
Problem is still existing

**Comment by T12z** [comment]
@stefan-karg was this related to EoA / SvL toggling (other issue)? Or does it still persist?

**Comment by stefan-karg** [comment]
I don't see any toggeling anymore. From my point of view the issue can be closed.
