### ISSUE TITLE
End of Mission: Radio Message not received at the EVC

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#913]
After changing from Level 2 to level ntc the radio message to disconnet from Radio is not seen.

**Comment by Rainer-Lampatzer** [comment]
Sorry, I cannot replicate this. Due to a segmentation fault in the testbench, I can not drive until the point where the error occurs.

![segmentationfault](https://cloud.githubusercontent.com/assets/14076350/11154498/0391a8ac-8a40-11e5-8ccc-a188cc8a92f9.jpg)

Even if this segmentation fault would not occur, it is time consuming to run the whole line for test of this feature only. **For a quicker way to find the error a slightly modified track file would be helpful**. This track file should have the fallback to NTC as early as possible, but not before pos. 4000.

Thanks a lot in advance for helping me and contributing to a quicker result.

**Comment by Rainer-Lampatzer** [comment]
I suggest to move (and rename) balise group 443 to the place of balise group 360 in the new track file. Thanks a lot in advance.

**Comment by JakobGartner** [comment]
I disagree

We have the hard requirement to use the original track topology with the original engineering . Only for additional scenarios (13-16) we can be creative 

However for demo economics we are using the original layout even there and will overlay the track with the US scenarios.

Mairamou and I are however working on modularising the track so that the different US can be looked at independently from each other

**Comment by BerndHekele** [comment]
I plan to repeat this test anyway. I will provide sufficient symptoms to solve the issue.

**Comment by Rainer-Lampatzer** [comment]
@JakobGartner 
I only need this for testing
Otherwise I have no way to analyze the problem as I can not replicate it.

> We have the hard requirement to use the original track topology with the original engineering .
> Only for additional scenarios (13-16) we can be creative

**Comment by JakobGartner** [comment]
Ok 

Then I think this will be covered by the modular track version

**Comment by Rainer-Lampatzer** [comment]
Thank U
Where can I find the modular track version?

**Comment by JakobGartner** [comment]
@Mairamou is working on it

**Comment by BerndHekele** [comment]
Here are some screenshots when the last 136 message is received at the RBC-System:
![image](https://cloud.githubusercontent.com/assets/3288918/11168176/bf0d0e60-8b84-11e5-99f1-b74f02a0e1c4.png)

Next layer (ping):
![image](https://cloud.githubusercontent.com/assets/3288918/11168185/045a2156-8b85-11e5-8416-9544033c2ba6.png)

**Comment by Rainer-Lampatzer** [comment]
Hi Bernd,

thank you for helping me.

According to the first picture, the session termination request (Msg 24 with packet 42) is sent.
Afterwards the flag is reset in order not to send this twice.

If it is lost on the way or inside the EVC, then I can change the logics so that the session termination request is repeated UNTIL the session has really been terminated.

I will start tomorrow in the late morning, so you still have time to decide.

I wish you a nice Sunday.

Rainer

**Comment by BerndHekele** [comment]
Dear Rainer,
the trigger is not sent in this scenario.  (trigger = false) The message is not triggered. As I see the problem the RBC needs to evaluate the valid flag og the packet which is part of the input.

**Comment by Rainer-Lampatzer** [comment]
Dear Bernd

thank you. 

> If it is lost on the way or inside the EVC, then I can change the logics so that the session termination 
> request is repeated UNTIL the session has really been terminated.
I did not implement this because nobody required. I introduced a force trigger instead.

Rainer

**Comment by BerndHekele** [comment]
Dear Rainer,
can you please tell me which model part is sending the trigger - just to see where the trigger shall come to live.

cu
Bernd

**Comment by Rainer-Lampatzer** [comment]
Hallo Bernd,

Im Fall einer EoM:

1. OBU sendet "End of Mission" (Msg 150)
2. RBC sendet "Session Management - Termination Request" (Msg 24 + Pkt 42)
3. OBU sendet "Termination" (Msg 156)
4. RBC sendet "Termination Acknowledgement" (Msg 39)

Ansonsten kann auch RBC selbst den Verbindungsabbruch initiieren und fängt mit 2. an.

VG, Rainer

**Comment by BerndHekele** [comment]
@Rainer-Lampatzer 
According to our user story the event is triggered by MSG 136 (Position Report with NTC information).
What makes you think about the Msg 150 as a start?

**Comment by Rainer-Lampatzer** [comment]
There is an "End of Mission " procedure that triggers the session termination by closing the desk.

The user story that terminates the sessioin in casre of level NTC is not covered by the SRS. Nevertheless I started implementing it.

According to the meeting of yesterday, the priority of this feature has been reduced in order to make new RBC messages for US13..15 first. 

What about the "modular track"?

**Comment by Rainer-Lampatzer** [comment]
RBC sends Packet 42, but EVC does not answer with a Msg 156.
In case the packet is expected with other values please inform me.

MSG 24 @32078.5 m
      nid_message: 24
          t_train: 1519800
            m_ack: 0
         nid_lrbg: 351
      t_train_ref: 0
           nid_em: 0
          q_scale: 0
             d_sr: 0
        t_sh_rqst: 0
            d_ref: 0
            q_dir: 0
        m_version: 15

0) Pkt042
       nid_packet: 42
            q_dir: 1
            q_rbc: 0
            nid_c: 426
          nid_rbc: 16383
        nid_radio: 500
   q_sleepsession: 0

**Comment by BerndHekele** [comment]
A correction in the position report (LRBG) solved the problem.
Solution is tested.
