### ISSUE TITLE
problem with type V_internal_Type

### ISSUE THREAD

**Issue by christianstahl** [openETCS/modeling#92]
The speed type as defined in Obu_Basic_Types seems to be inadequate. It is defined as an integer in km/h. In appendix 3.1 (chapter 3), we need to consider constants of e.g. 7.5 km/h. Therefore, I would prefer to have the type to be redefined in m/s.
@BerndHekele @Farhangi

**Comment by JakobGartner** [comment]
In order to stay consistent and to ease reviews, we should stay in one unit system, which should be consistent across the entire model.
We should also consider that we have a functional model which should probably ignore any target- specific scaling etc., and also avoid to have km/h in one place and m/s in another.

If the SRS “thinks” in km/h, we would ease reviews and validation by staying in km/h.

Would, for the moment, a type in 0,1km/h be adequate?

**Comment by vgontier** [comment]
Braking curve calculation is done in m/s, which is compliant with the international measurement system. Review is important but curve calculation is very complex. I don't think it would be a good idea to complicate it a lot more whith a change of unit.
But it's only my point of view.

**Comment by JakobGartner** [comment]
Ok 

Keep your point of view then, very fine with me.



Mit freundlichen Grüßen 
Cordialement
Best regards 

Jakob Gärtner 
GF/ PDG
Local Energy Appliances
Am Mittleren Moos 48
86167 Augsburg 
Germany
+49 821 907802-20
+49 151 25387841

Local Energy (Cameroon) Sarl 
BP 14000
Yaoundé 
Cameroun 
+237 6 98 29 16 01

j.gaertner@lea-energy.com

**Comment by christianstahl** [comment]
How precise should the values be? For example, 7.5km/h are 2.083333 m/s. So if the data type used is an integer, a type where 1 is equal to 0,01m/s or even 0,001m/s might be necessary.

**Comment by JakobGartner** [comment]
As a very general remark, as we are on a pure simulation model, it could have been a good idea (from the beginning) to stay with float data types.
This would have simplified many issues and would have enabled a model purely in the problem domain (leaving implementation to a given HW architecture to a future step).

As we are have already advanced in this direction, and the SRS also partly building on scaled integer types, I would suggest that we stay with our current approach.

We should be aware that scaled integer is a potentially tricky issue, the questions not only being limited to precision, but also to range, overflow, underflow, what happens when operators are needed for differently scaled data flows etc.

This is also a question for WP4-

**Comment by BerndHekele** [comment]
We should involve @UweSteinkeFromSiemens  in this issue.
In the SRS both types are used for different use-cases. 
If it is more convenient for you you could use internally a new type with /s. But at the edges of your model we need to do a conversion.

**Comment by BenjaminBeichler** [comment]
I like the Idea to have floating types, because there are much more handy to translate from SRS. As Jakob already mentioned, the integer types introduce unnecessary complexity for a functional model at this state of the project. It would also fulfill the "don't optimize" propose of Uwe.

When switching to fixed point datatypes, what is the effective result of such integer types, there also exist efficient (and maybe already verified) c-libraries, which could be used in some far future with scade.

**Comment by JakobGartner** [comment]
I propose the following solution (applies also to #93):


The types as defined in the SRS are mainly relevant for interfacing the API. (the SRS being track- centric…)

As soon as the data are in our system, we format them in the most convenient way for our purposes.

This means for each subsystem/workgroup that they define their datatypes locally as needed (for example in train supervision/ braking curves m/s in float) and in BG handling scaled integers as in the SRS // take this only as examples, draw your own conclusions locally.

I will then, on the integration level, optimise/minimise the necessary type conversions.


For the ETCS language this could mean: use the scaled integers as in the SRS. 
It also means that inside the kernel this may be quickly converted for optimal treatment.


For a possible HW integration there would then be different implementations (for example a 16bit fixed point scaling for old HW), but this is not relevant yet.

Let’s treat our reference SW as a HW- independent executable SW specification (=model)

**Comment by MERCEmentre** [comment]
Hello,

I'm discovering this discussion through issue #93. The problem of handling multiple units and computation precision is not new and unfortunately far from being solved.

Regarding computation precision, as far as I know (in Japanese and European SW), in embedded safety critical railway software floating point computations are not allowed because is it too complex to ensure their correctness (due to rounding errors, different behaviour of floating point algorithm vs. their math real counterpart, ...). Proving correctness of floating point computation is nowadays possible but is *very* expensive and complex (e.g. see work at CEA List & Polytechnique on Fluctuat or work at INRIA Toccata team). Only integer computations are used. In language like Ada, fixed point can be used (which corresponds to integers used with a suitable library). Of course, if you don't want to do SIL4 software, floating point is fine.

Regarding handling of different units, due to lacking of support for unit systems in languages, usually one defines a suitable unit system (e.g. cm/s in railway) and using only it in the whole program. The language landscape is changing though, nowadays F# (http://blogs.msdn.com/b/andrewkennedy/archive/2008/08/29/units-of-measure-in-f-part-one-introducing-units.aspx), Ada 2012 ((http://www.adacore.com/adaanswers/gems/gem-136-how-tall-is-a-kilogram/) or even in some extensions to C (http://mbeddr.com/) are handling units and detecting errors at compilation time.

For SCADE, Esterel Technologies made an experiment a few years ago (see paper from Schlick et al., "Checking SCADE Models for Correct Usage of Physical Units" http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.87.699) but I don't know if this technology is integrated in current SCADE or not.

My recommendations from a correctness verification point of view:
* Stick to a single physical unit system except if your modelling or target language supports checking of physical units at compilation time;
* Stick to integer computation for SIL4 software, floating point otherwise. Define a suitable precision and use only it.

Best regards,
david

**Comment by JakobGartner** [comment]
Hello David,

I fully agree with all your remarks about safety aspects and best practices as far as floating point & SIL4 is concerned.

Remarks: 

The Esterel experiment you mentioned did not lead to any such solution. There were also discussions to integrate Fluctuat with SCADE, but this was not done.

There is meanwhile an Ada KCG which also supports SPARK which in turn allows for formal verification of some numerical properties

As from the next SCADE Release, (R16) manual implementation of fixed point (with a wide choice of data types) will be possible on model level (for now it is only on library level)



openETCS context

We are not aiming to build a vital system. We are building a functional, executable reference model, which will primarily run in host simulation mode.

If at a later stage this reference model shall be used as an input to a SIL4 compliant SW development process, this will have to take the actual target HW into account, which is yet unknown.
Anything from vintage 16bit HW to a certified FPU / FPGA is imaginable 

—> we should keep our model IMPLEMENTATION AGNOSTIC
—> we anyway will never have the time to solve numerical precision issues (even if we assume an ideal target HW)

—> we should go for float units wherever this eases the task of building a functional reference model



Jakob

**Comment by UweSteinkeFromSiemens** [comment]
At the beginning, we started with floating point (see Subset 026 conversions to XML, C and SCADE) to ease prototyping and offload from dealing with integer arithmetic problems. But then, WP 2 (if I remember correctly) insisted on integer types ...

**Comment by UweSteinkeFromSiemens** [comment]
For distances, locations and positions, integer arithmetic is quite more appropriate than floating point, since the accumulation of large values does not reduce precision.

**Comment by JakobGartner** [comment]
To ease this discussion:

- Nobody should change now his work. If you started with integer, stay on integer

- For API types, we should use the SRS scalings and types

- For newly created functions, choose the locally best representation 


Is that something we can agree on, knowing that we are NOT going to have a SIL4 system in this project?


If nobody objects, I would say we close this issue.

**Comment by UweSteinkeFromSiemens** [comment]
I don't object.

**Comment by MariellePetitDoche** [comment]
Assumption "knowing that we are NOT going to have a SIL4 system in this project" might be discussed a long...


"We are not aiming to build a vital system. We are building a functional, executable reference model, which will primarily run in host simulation mode." is maybe the goal of some partners, not the goal of the majority of partners of the project and the initial goal of the project.

**Comment by BerndHekele** [comment]
We have a solution for the originally posted requirement.
I would like to close this issue even thou there has been a lot of discussion ongoing alongside.
