### ISSUE TITLE
openETCS simCTRL showing messages in wrong sequence

### ISSUE THREAD

**Issue by BerndHekele** [openETCS/modeling#921]
Dear Johannes,
I just recognised the messages in the simCTRL window are in wrong sequence:
![image](https://cloud.githubusercontent.com/assets/3288918/11237016/87d0b6f8-8ddd-11e5-9f24-3a21121b7017.png)

Message32 is sent by the EVC after receiving message 155.

**Comment by jokaICS** [comment]
Ah, yes...
The problem here is that in our simulation the RBC can actually respond to a message from the EVC within the same cycle. And if two messages (one from the EVC, one from the RBC) are present in the same cycle, they are sent to the SimCtrl UI in a fixed order determined by the C-Code (currently we send RBC messages before Train messages). I can switch the ordering, but then we would probably have the inverse problem (EVC responds before RBC message was sent).

So we need a more elaborate algorithm to decide, which message should be displayed first. Do you have any ideas?

**Comment by BerndHekele** [comment]
We can add delay operators in the scade model of the environment to simulate radio gap.

**Comment by BerndHekele** [comment]
Solution available
