### ISSUE TITLE
Not MA after ~26934m?

### ISSUE THREAD

**Issue by jokaICS** [openETCS/modeling#924]
I'm currently stuck at ~27km (resticted to 14 kph); possibly due to a missing MA?.
Here are the last few targets as calculated by SDM:

![image](https://cloud.githubusercontent.com/assets/13429700/11246178/dba04986-8e16-11e5-9789-213ec1031086.png)

Can anybody confirm this issue?

BTW: why does the target type toggle repeatedly between EoA and SvL at ~26850m? @T12z

**Comment by JakobGartner** [comment]
which track? nominal or “modular” ?

**Comment by jokaICS** [comment]
Sorry for the incomplete bug report: nominal.

**Comment by T12z** [comment]
this EoA/SvL toggling is same strange behaviour as I just noticed in #919 
The SvL is always double the distance of EoA :confused: 
Is there some issue with incomplete messages??

**Comment by jokaICS** [comment]
The changes to SDM partially mitigated the EoA/SvL toggling. However, the MA problem remains: the MA sent by the RBC @ 22756m (~100m beyond BG416) seems to be ignored by the EVC:
![image](https://cloud.githubusercontent.com/assets/13429700/11265825/ced7487e-8e9f-11e5-8787-bc4713ca4bb0.png)

Maybe this is due to linking errors? I don't know where to look to identify these issues...

**Comment by JakobGartner** [comment]
As just discussed with Bernd, 

no changes pushed from TrackAtlas since about 4 weeks 



We will look fir discrepancies on the track


This may be linked to the bad data introduced by the bogus BG (“0”) we found and transcribed from the JRU data (where also the link distance was not fitting the rest of the data and which was not present in the different packets covering the same area

**Comment by jokaICS** [comment]
The latest updates didn't solve the problem. The MA sent (and acknowledged) 100m after BG416 does not take effect.

**Comment by BerndHekele** [comment]
This error is also visible in the new build.
Last Msg 3 is sent at m 22752
![image](https://cloud.githubusercontent.com/assets/3288918/11278001/553ed492-8ee9-11e5-875e-e68bc1139957.png)

We see the EB - this implies we have EOA reached.
Unfortunately, no SDM input in Debug window due to optimisation.
We see the reference of the Message is also passed already - may we have a problem caused by a wrong refference point.

**Comment by BerndHekele** [comment]
@JakobGartner 
Update to this issue:
We have an track error here: the direction of the packets 15 and 21 is wrong in this place.
![image](https://cloud.githubusercontent.com/assets/3288918/11299766/b92a3e56-8f89-11e5-9080-3989b80d4966.png)

Can you please check with the original JRU and update the packets accordingly?

**Comment by JakobGartner** [comment]
Ok

**Comment by BerndHekele** [comment]
I see a similar picture in the trackviewer for other LRBGs:
LRBG 426:
![image](https://cloud.githubusercontent.com/assets/3288918/11300170/34008380-8f8d-11e5-9d16-da6c78c59451.png)
LRBG 431:
![image](https://cloud.githubusercontent.com/assets/3288918/11300284/0e5ab8fc-8f8e-11e5-951a-990324f9b576.png)

I will provide quick-fixes for these problems.

**Comment by BerndHekele** [comment]
I jusr pushed corrections for the track.
@jokaICS 
Can you please update the track for the viewer as well?
Thanks.

kr
Bernd

**Comment by jokaICS** [comment]
done.

**Comment by T12z** [comment]
@jokaICS please close if finished

**Comment by jokaICS** [comment]
Solved.
