### ISSUE TITLE
The  version check and the value range check of recived messages

### ISSUE THREAD

**Issue by Farhangi** [openETCS/modeling#94]
where (in the model) should the following checks

- version check (M_VERSION)
- value range check of variables
- invalid and spare value

 be implemented.

@MERCEmentre 
@VNuhaan 
@BaseliyosJacob 
@JanWelvaarts

**Comment by VNuhaan** [comment]
Dear Peyman,

M_VERSION tells the onboard unit how the bitstream form balise/RBC must be read (chapters 6, 7 and 8). So the bitwalker needs this M_VERSION. The bitwalker can find M_VERSION is inside the balise telegram  For RBC messages is this different. M_VERSION is then sent to the onboard when building up the connection, so the onboard needs to remember the M_VERSION of the RBC. Please be aware that the onboard unit can have connections with more than one RBC.

Check on value range I don’t understand. Where is this check written in the SRS?

The check on spare values can be put some ware between the bitwalker and mode/level filtering. I think the best place is to implement the check inside the bitwalker.

Best regards,

Vincent

Van: Peyman Farhangi [mailto:notifications@github.com]
Verzonden: vrijdag 30 januari 2015 10:27
Aan: openETCS/modeling
CC: Nuhaan, Vincent
Onderwerp: [modeling] The version check and the value range check of recived received messages (#94)


where (in the model) should the following checks

  *   version check (M_VERSION)
  *   value range check of variables

·         invalid and sperr value

be implemented.
@MERCEmentre<https://github.com/MERCEmentre>
@VNuhaan<https://github.com/VNuhaan>

—
Reply to this email directly or view it on GitHub<https://github.com/openETCS/modeling/issues/94>.

________________________________
Lloyd’s Register is a trading name of Lloyd’s Register Group Limited and its subsidiaries. For further details please see http://www.lr.org/entities © Lloyd's Register Group Limited 2012

Lloyd's Register Group Limited, its affiliates and subsidiaries and their respective officers, employees or agents are, individually and collectively, referred to in this clause as 'Lloyd's Register'. Lloyd's Register assumes no responsibility and shall not be liable to any person for any loss, damage or expense caused by reliance on the information or advice in this document or howsoever provided, unless that person has signed a contract with the relevant Lloyd's Register entity for the provision of this information or advice and in that case any responsibility or liability is exclusively on the terms and conditions set out in that contract.

**Comment by MERCEmentre** [comment]
Hello,
I would put the value range check at the same place that the invalid or spare value check. Ideally at the model boundary, so only valid values are sent into the model.
Best regards,
david

**Comment by BerndHekele** [comment]
I believe this issue is closed and implemented.
