### ISSUE TITLE
Test report 01.12.- disappering of CSG red/yellow

### ISSUE THREAD

**Issue by Farhangi** [openETCS/modeling#949]
@Rainer-Lampatzer @T12z @ShuangjiaoCao 

 at km 4811 

CSG is disappearing red/yellow/white
![image](https://cloud.githubusercontent.com/assets/2284296/11507272/81aaf61e-9853-11e5-9082-a665491de3e8.png)

**Comment by T12z** [comment]
I am sorry Peyman, I really have problems understanding your issue. 
First up, I have noticed some inconsistency here as well for quite some time. And I also see SDM as potential root cause.
But can you please explain briefly the correct expected behaviour? The description in my section 3.9 is not too exhaustive about this. 
Cheers *!*

---- Peyman Farhangi schrieb ----

**Comment by ShuangjiaoCao** [comment]
![image](https://cloud.githubusercontent.com/assets/7654856/11627550/a2e0286c-9ceb-11e5-98e6-7185a6a07139.png)
![image](https://cloud.githubusercontent.com/assets/7654856/11627591/fd90fb06-9ceb-11e5-9696-964ffd74898c.png)



I guess the problem was in PacketDynamic.v_intervention. As the image shows, the Intervention Speed is -1, which makes the CSG disappeared.

**Comment by T12z** [comment]
I **suspect** a diverging behaviour between DMI and brake calculation. From SDM's point of view, after braking, v_perm and v_interv rise again - this correct by the specified calculations. But it was asked, that v_perm and v_interv do not rise within same TSM. But since all speed limits rised -- just not on DMI -- no intervention is shown. So far *unconfirmed suspicions*. Same issue points towards different sized warning gauge sectors.
Root issue: the right way to prevent TSM-speeds from rising is not specified in the SRS. And the current quick-fix seems to carry a few caveats. I am afraid this will need more thought to do it right.

**Comment by JakobGartner** [comment]
From TrackAtlas point of view, DMI and SDM receive exactly the same data, with the exception that the data for SDM are not truncated at EOA. Might this difference contribute to the problem?

**Comment by T12z** [comment]
above mentioned quick-fix was removed together with brake-build-up trimming
