### ISSUE TITLE
Position report: incorrect value for v_train

### ISSUE THREAD

**Issue by jokaICS** [openETCS/modeling#952]
It seems to me that the value for v_train in P000/P001 is incorrect: for a speed of ~10 km/h P000 reports v_train=58 instead of v_train=2 (i.e. v is multiplied by 5 instead of divided by 5).

**Comment by JakobGartner** [comment]
Will have a look 

(You work too long.)

**Comment by BerndHekele** [comment]
I checked the implementation in ProvidePosition Report - this is correct.
@JakobGartner 
Cab we have a correction in the track messages?

**Comment by JakobGartner** [comment]
The issue is here (probably, if I understand the position report implementation right) that V_TRAIN comes in cm/s and the TrackMessages library expects in km/h. The operator CAST_V_TRAIN_to_Int is actually dividing by 5. 
Can you confirm this theory? Question...: The V_TRAIN built by ProvidePositionReport has which scaling?

**Comment by BerndHekele** [comment]
I provided a correction in the position-report.

**Comment by jokaICS** [comment]
Solved.
